from django.core.management.base import BaseCommand
from loyiha.models import (
    Kategoriya, Qadam, FavquloddaRaqam, TestSavol,
    BolalarMavzu, BolalarQadam, BolalarOgohlantirish, BolalarMalumot,
)


class Command(BaseCommand):
    help = "Boshlang'ich ma'lumotlarni yuklash"

    def handle(self, *args, **options):
        # Favqulodda raqamlar
        raqamlar = [
            ("Tez yordam", "103", "🚑", 1),
            ("O't o'chirish", "101", "🚒", 2),
            ("Militsiya", "102", "👮", 3),
            ("Gaz xizmati", "104", "🔥", 4),
            ("Favqulodda vaziyatlar", "1050", "🆘", 5),
        ]
        for nomi, raqam, icon, tartib in raqamlar:
            FavquloddaRaqam.objects.get_or_create(
                raqam=raqam,
                defaults={'nomi': nomi, 'icon': icon, 'tartib': tartib}
            )
        self.stdout.write(self.style.SUCCESS("Favqulodda raqamlar yuklandi"))

        # ===== KATEGORIYALAR VA QADAMLAR =====

        # 1. Qon ketish
        kat1, _ = Kategoriya.objects.get_or_create(
            nomi="Qon ketish",
            defaults={
                'icon': '🩸', 'rang': '#e74c3c', 'tartib': 1,
                'tavsif': "Jarohat natijasida qon ketganda nima qilish kerak"
            }
        )
        qadamlar_1 = [
            (1, "Qo'lqop kiying", "Agar imkoni bo'lsa, plastik qo'lqop yoki toza naylon paket kiying. Bu infeksiyadan himoya qiladi.", False,
             "Birinchi navbatda qo'lqop kiying. Bu sizni va jabrlanuvchini infeksiyadan himoya qiladi."),
            (2, "Jarohat joyini bosib turing", "Toza mato yoki bint bilan jarohat joyini mahkam bosib turing. 10-15 daqiqa davomida qo'yib yubormang.", True,
             "Toza mato bilan jarohat joyini mahkam bosib turing! 10-15 daqiqa qo'yib yubormang!"),
            (3, "Jarohat joyini yuqori ko'taring", "Agar qo'l yoki oyoq jarohatlangan bo'lsa, uni yurak darajasidan yuqori ko'taring. Bu qon ketishni kamaytiradi.", False,
             "Jarohatlangan joyni yuqori ko'taring. Bu qon ketishni kamaytiradi."),
            (4, "Bintni almashtirishdan saqlaning", "Agar bint qonga to'lsa, ustiga yana bir qavat qo'ying. Ostidagini olib tashlamang!", True,
             "Diqqat! Bintni almashtirishdan saqlaning. Ustiga yangi qavat qo'ying!"),
            (5, "103 ga qo'ng'iroq qiling", "Agar qon ketish to'xtamasa yoki jarohat chuqur bo'lsa, darhol tez yordam chaqiring.", True,
             "103 ga qo'ng'iroq qiling! Tez yordam chaqiring!"),
        ]
        for tartib, sarlavha, tavsif, muhim, ovoz in qadamlar_1:
            Qadam.objects.get_or_create(
                kategoriya=kat1, tartib=tartib,
                defaults={'sarlavha': sarlavha, 'tavsif': tavsif, 'muhim': muhim, 'ovozli_matn': ovoz}
            )

        # 2. Kuyish
        kat2, _ = Kategoriya.objects.get_or_create(
            nomi="Kuyish",
            defaults={
                'icon': '🔥', 'rang': '#e67e22', 'tartib': 2,
                'tavsif': "Issiq narsa, olov yoki kimyoviy moddadan kuyib qolganda nima qilish kerak"
            }
        )
        qadamlar_2 = [
            (1, "Kuyish manbasidan uzoqlashing", "Darhol issiqlik manbasidan uzoqlashing. Yonayotgan kiyimni yechib tashlang (teriga yopishgan bo'lmasa).", True,
             "Darhol issiqlik manbasidan uzoqlashing!"),
            (2, "Sovuq suv bilan sovuting", "Kuygan joyni 10-20 daqiqa davomida oqar sovuq suv ostida ushlab turing. Muz qo'ymang!", True,
             "Kuygan joyni 10-20 daqiqa sovuq suv ostida ushlab turing. Muz qo'ymang!"),
            (3, "Kiyim va taqinchoqlarni yechib oling", "Kuygan joy atrofidagi kiyim, uzuk, soat va boshqa taqinchoqlarni ehtiyotlik bilan yechib oling.", False,
             "Kuygan joy atrofidagi kiyim va taqinchoqlarni ehtiyotlik bilan yechib oling."),
            (4, "Pufakchalarni yorib tashlamang", "Agar pufakchalar paydo bo'lsa, ularni ASLO yorib tashlamang. Bu infeksiya kiritishi mumkin.", True,
             "Diqqat! Pufakchalarni aslo yorib tashlamang! Bu xavfli!"),
            (5, "Toza bint bilan o'rang", "Kuygan joyni steril bint yoki toza mato bilan yumshoq o'rang. Paxta qo'ymang.", False,
             "Kuygan joyni toza bint bilan yumshoq o'rang."),
            (6, "Shifokorga murojaat qiling", "Katta kuyishlarda, bolalar yoki keksalarda darhol 103 ga qo'ng'iroq qiling.", False,
             "Katta kuyishlarda darhol 103 ga qo'ng'iroq qiling."),
        ]
        for tartib, sarlavha, tavsif, muhim, ovoz in qadamlar_2:
            Qadam.objects.get_or_create(
                kategoriya=kat2, tartib=tartib,
                defaults={'sarlavha': sarlavha, 'tavsif': tavsif, 'muhim': muhim, 'ovozli_matn': ovoz}
            )

        # 3. Hushdan ketish
        kat3, _ = Kategoriya.objects.get_or_create(
            nomi="Hushdan ketish",
            defaults={
                'icon': '😵', 'rang': '#9b59b6', 'tartib': 3,
                'tavsif': "Odam hushidan ketganda yoki bexush holatda nima qilish kerak"
            }
        )
        qadamlar_3 = [
            (1, "Xavfsizlikni tekshiring", "Atrofda xavf yo'qligiga ishonch hosil qiling. Jabrlanuvchiga yaqinlashing.", False,
             "Avval atrofda xavf yo'qligini tekshiring."),
            (2, "Jabrlanuvchini tekshiring", "Yelkasidan ushlab, \"Sizga yaxshimi?\" deb so'rang. Javob bermasa keyingi qadamga o'ting.", True,
             "Jabrlanuvchini yelkasidan ushlab, sizga yaxshimi deb so'rang."),
            (3, "103 ga qo'ng'iroq qiling", "Darhol tez yordamni chaqiring. Manzilni aniq ayting.", True,
             "Darhol 103 ga qo'ng'iroq qiling! Manzilni aniq ayting!"),
            (4, "Nafas olishini tekshiring", "Boshini orqaga engashtiring, iyagini ko'taring. 10 soniya davomida nafas olishini kuzating.", True,
             "Boshini orqaga engashtiring. 10 soniya davomida nafas olishini tekshiring."),
            (5, "Nafas olsa - yon holatga yotqizing", "Agar nafas olayotgan bo'lsa, jabrlanuvchini yon holatga (tiklash holatiga) yotqizing.", False,
             "Agar nafas olayotgan bo'lsa, yon holatga yotqizing."),
            (6, "Nafas olmasa - yurak massaji boshlang", "Agar nafas olmasa, ko'krak qafasining o'rtasiga qo'llarni qo'yib, daqiqasiga 100-120 marta bosing.", True,
             "Agar nafas olmasa, yurak massajini boshlang! Ko'krak qafasini daqiqasiga 100-120 marta bosing!"),
        ]
        for tartib, sarlavha, tavsif, muhim, ovoz in qadamlar_3:
            Qadam.objects.get_or_create(
                kategoriya=kat3, tartib=tartib,
                defaults={'sarlavha': sarlavha, 'tavsif': tavsif, 'muhim': muhim, 'ovozli_matn': ovoz}
            )

        # 4. Suyak sinishi
        kat4, _ = Kategoriya.objects.get_or_create(
            nomi="Suyak sinishi",
            defaults={
                'icon': '🦴', 'rang': '#2c3e50', 'tartib': 4,
                'tavsif': "Suyak sinishi yoki chiqishi gumon qilinganda nima qilish kerak"
            }
        )
        qadamlar_4 = [
            (1, "Harakatlanishdan saqlang", "Singan joyni qimirlatmang! Jabrlanuvchini ko'chirmasdan yordam bering.", True,
             "Singan joyni aslo qimirlatmang!"),
            (2, "Singan joyni mahkamlang", "Tayoqcha, karton yoki boshqa qattiq narsa bilan singan joyni harakatsiz holda mahkamlang (shina qo'ying).", False,
             "Tayoqcha yoki qattiq narsa bilan singan joyni mahkamlang."),
            (3, "Sovuq bosing", "Muz yoki sovuq narsani mato orqali singan joyga bosing. Shishni kamaytiradi.", False,
             "Sovuq narsani mato orqali singan joyga bosing."),
            (4, "103 ga qo'ng'iroq qiling", "Tez yordam chaqiring. Jabrlanuvchini o'zingiz ko'chirmasdan professional yordam kuting.", True,
             "103 ga qo'ng'iroq qiling va professional yordam kuting!"),
        ]
        for tartib, sarlavha, tavsif, muhim, ovoz in qadamlar_4:
            Qadam.objects.get_or_create(
                kategoriya=kat4, tartib=tartib,
                defaults={'sarlavha': sarlavha, 'tavsif': tavsif, 'muhim': muhim, 'ovozli_matn': ovoz}
            )

        # 5. Zaharlanish
        kat5, _ = Kategoriya.objects.get_or_create(
            nomi="Zaharlanish",
            defaults={
                'icon': '☠️', 'rang': '#27ae60', 'tartib': 5,
                'tavsif': "Oziq-ovqat yoki kimyoviy moddadan zaharlanish alomatlari va yordam"
            }
        )
        qadamlar_5 = [
            (1, "Zahar manbasini aniqlang", "Nima iste'mol qilinganini aniqlang. Idish yoki o'ramani saqlang - shifokorga ko'rsatish uchun.", True,
             "Nima iste'mol qilinganini aniqlang va idishni saqlang."),
            (2, "103 ga qo'ng'iroq qiling", "Darhol tez yordamni chaqiring. Nimani va qancha iste'mol qilganini ayting.", True,
             "Darhol 103 ga qo'ng'iroq qiling!"),
            (3, "Qustirishdan saqlaning", "Shifokor ruxsatisiz qustirmang! Ayniqsa kislota yoki ishqor zaharlanishida qustirish xavfli.", True,
             "Diqqat! Shifokor ruxsatisiz qustirmang! Bu xavfli bo'lishi mumkin!"),
            (4, "Jabrlanuvchini kuzating", "Nafas olishi va hushini kuzatib turing. Hushidan ketsa yon holatga yotqizing.", False,
             "Nafas olishi va hushini kuzatib turing."),
        ]
        for tartib, sarlavha, tavsif, muhim, ovoz in qadamlar_5:
            Qadam.objects.get_or_create(
                kategoriya=kat5, tartib=tartib,
                defaults={'sarlavha': sarlavha, 'tavsif': tavsif, 'muhim': muhim, 'ovozli_matn': ovoz}
            )

        # 6. Bo'g'ilish (tiqilib qolish)
        kat6, _ = Kategoriya.objects.get_or_create(
            nomi="Bo'g'ilish",
            defaults={
                'icon': '😤', 'rang': '#3498db', 'tartib': 6,
                'tavsif': "Tomog'iga narsa tiqilib qolsa va nafas olish qiyinlashsa nima qilish kerak"
            }
        )
        qadamlar_6 = [
            (1, "Yo'talishga undang", "Agar odam yo'tala olsa, uni kuchli yo'talishga undang. Bu eng samarali usul.", False,
             "Avval kuchli yo'talishga undang."),
            (2, "Orqasiga 5 marta uring", "Jabrlanuvchini oldinga engashtiring. Kurak suyaklari orasiga kaft bilan 5 marta kuchli uring.", True,
             "Jabrlanuvchini oldinga engashtiring va kurak suyaklari orasiga 5 marta kuchli uring!"),
            (3, "Geymlix usulini qo'llang", "Orqasidan quchoqlang, musht tugib qorin ustiga qo'ying, ikkinchi qo'l bilan bosib yuqoriga torting. 5 marta.", True,
             "Geymlix usuli: orqasidan quchoqlang, qorin ustiga musht qo'yib yuqoriga 5 marta torting!"),
            (4, "Takrorlang yoki 103 ga qo'ng'iroq qiling", "5 orqa urish va 5 Geymlix usulini navbatma-navbat takrorlang. Natija bo'lmasa 103 ga qo'ng'iroq qiling.", True,
             "Takrorlang. Natija bo'lmasa 103 ga qo'ng'iroq qiling!"),
        ]
        for tartib, sarlavha, tavsif, muhim, ovoz in qadamlar_6:
            Qadam.objects.get_or_create(
                kategoriya=kat6, tartib=tartib,
                defaults={'sarlavha': sarlavha, 'tavsif': tavsif, 'muhim': muhim, 'ovozli_matn': ovoz}
            )

        self.stdout.write(self.style.SUCCESS("Kategoriyalar va qadamlar yuklandi"))

        # ===== TEST SAVOLLARI =====
        savollar = [
            {
                'savol': "Qon ketayotganda birinchi nima qilish kerak?",
                'a': "Suv quyish kerak",
                'b': "Toza mato bilan bosib turish kerak",
                'c': "Qo'yib berish kerak, o'zi to'xtaydi",
                'd': "Spirt surtish kerak",
                'togri': 'b',
                'izoh': "Qon ketayotganda toza mato bilan jarohat joyini mahkam bosib turish eng to'g'ri usuldir.",
                'kat': kat1,
            },
            {
                'savol': "Kuygan joyga nima qo'yish MUMKIN EMAS?",
                'a': "Sovuq suv",
                'b': "Toza bint",
                'c': "Muz to'g'ridan-to'g'ri",
                'd': "Steril bog'lam",
                'togri': 'c',
                'izoh': "Muzni to'g'ridan-to'g'ri kuygan joyga qo'yish to'qimani yanada shikastlaydi. Faqat sovuq suv ishlatiladi.",
                'kat': kat2,
            },
            {
                'savol': "Odam hushidan ketsa, birinchi navbatda nima qilasiz?",
                'a': "Yuziga suv sepaman",
                'b': "Xavfsizlikni tekshirib, javob berishini so'rayman",
                'c': "Ko'tarib yugurib kasalxonaga olib boraman",
                'd': "Hech narsa qilmayman",
                'togri': 'b',
                'izoh': "Avval atrofdagi xavfsizlikni tekshirib, keyin jabrlanuvchining holatini baholash kerak.",
                'kat': kat3,
            },
            {
                'savol': "Suyak singanda nima qilish MUMKIN EMAS?",
                'a': "Singan joyni mahkamlash",
                'b': "103 ga qo'ng'iroq qilish",
                'c': "Singan suyakni o'rniga solishga harakat qilish",
                'd': "Sovuq bosish",
                'togri': 'c',
                'izoh': "Singan suyakni o'zingiz o'rniga solishga ASLO harakat qilmang! Bu nerv va qon tomirlarini shikastlashi mumkin.",
                'kat': kat4,
            },
            {
                'savol': "Zaharlanishda shifokor ruxsatisiz nima qilish xavfli?",
                'a': "Suv ichirish",
                'b': "Qustirishga harakat qilish",
                'c': "103 ga qo'ng'iroq qilish",
                'd': "Dam oldirishga yotqizish",
                'togri': 'b',
                'izoh': "Kislota yoki ishqor zaharlanishida qustirish qizilo'ngachni qayta kuydirib, holatni yomonlashtirishi mumkin.",
                'kat': kat5,
            },
            {
                'savol': "Tez yordam telefon raqami qancha?",
                'a': "101",
                'b': "102",
                'c': "103",
                'd': "104",
                'togri': 'c',
                'izoh': "O'zbekistonda tez yordam raqami 103. 101 - o't o'chirish, 102 - militsiya, 104 - gaz xizmati.",
                'kat': None,
            },
            {
                'savol': "Yurak massajida daqiqasiga necha marta bosish kerak?",
                'a': "50-60 marta",
                'b': "70-80 marta",
                'c': "100-120 marta",
                'd': "150-200 marta",
                'togri': 'c',
                'izoh': "Yurak massajida daqiqasiga 100-120 marta bosish tavsiya etiladi.",
                'kat': kat3,
            },
            {
                'savol': "Kuygan joyni sovuq suvda qancha vaqt ushlab turish kerak?",
                'a': "1-2 daqiqa",
                'b': "5 daqiqa",
                'c': "10-20 daqiqa",
                'd': "1 soat",
                'togri': 'c',
                'izoh': "Kuygan joyni 10-20 daqiqa davomida oqar sovuq suv ostida ushlab turish tavsiya etiladi.",
                'kat': kat2,
            },
            {
                'savol': "Geymlix usuli nimaga ishlatiladi?",
                'a': "Qon to'xtatishga",
                'b': "Suyak sinishiga",
                'c': "Tomog'iga narsa tiqilib qolishga",
                'd': "Kuyishga",
                'togri': 'c',
                'izoh': "Geymlix (Heimlich) usuli tomog'iga yot jism tiqilib qolganida, bo'g'ilish xavfida qo'llaniladi.",
                'kat': kat6,
            },
            {
                'savol': "Bexush odamni qaysi holatda yotqizish kerak?",
                'a': "Chalqancha",
                'b': "O'tirgizish kerak",
                'c': "Yon holatda (tiklash holati)",
                'd': "Oyoq tomonini ko'tarish kerak",
                'togri': 'c',
                'izoh': "Bexush lekin nafas olayotgan odamni yon holatga (tiklash holatiga) yotqizish kerak. Bu til tushib nafas yo'lini berkitishini oldini oladi.",
                'kat': kat3,
            },
        ]
        savollar += [
            {
                'savol': "Yurak to'xtashi aniqlanganda birinchi navbatda nima qilish kerak?",
                'a': "Suv ichirish",
                'b': "Yuziga suv sepish",
                'c': "Yurak-o'pka resusitatsiyasini boshlash",
                'd': "Karovatga yotqizish",
                'togri': 'c',
                'izoh': "Yurak to'xtashida darhol yurak-o'pka resusitatsiyasi (YOR) boshlash hayotni saqlab qoladi.",
                'kat': kat3,
            },
            {
                'savol': "Sun'iy nafas berishda necha soniyada bir marta nafas beriladi?",
                'a': "Har 2 soniyada",
                'b': "Har 5 soniyada",
                'c': "Har 10 soniyada",
                'd': "Har 30 soniyada",
                'togri': 'b',
                'izoh': "Sun'iy nafas berishda har 5-6 soniyada bir marta (daqiqasiga 10-12 marta) nafas beriladi.",
                'kat': kat3,
            },
            {
                'savol': "Yurak massajida qo'lni ko'krak qafasining qayeriga qo'yish kerak?",
                'a': "Yuqori qismiga",
                'b': "O'rtasiga (to'sh suyagining pastki yarmiga)",
                'c': "Chap tomoniga",
                'd': "Qorin ustiga",
                'togri': 'b',
                'izoh': "Qo'lni ko'krak qafasining o'rtasiga, to'sh suyagining pastki yarmiga qo'yish kerak.",
                'kat': kat3,
            },
            {
                'savol': "Jabrlanuvchi nafas olmayotgan bo'lsa, 30 ta ko'krak bosishga nechta sun'iy nafas beriladi?",
                'a': "30:1",
                'b': "15:2",
                'c': "30:2",
                'd': "10:2",
                'togri': 'c',
                'izoh': "Zamonaviy YOR standartiga ko'ra, 30 ta ko'krak bosishga 2 ta sun'iy nafas beriladi (30:2 nisbat).",
                'kat': kat3,
            },
            {
                'savol': "Birinchi daraja kuyish qanday ko'rinadi?",
                'a': "Pufakchalar paydo bo'ladi",
                'b': "Teri qorayadi",
                'c': "Faqat qizarish va og'riq",
                'd': "Teri ko'chib ketadi",
                'togri': 'c',
                'izoh': "Birinchi daraja kuyishda faqat teri qizaradi va og'riq seziladi. Pufakchalar ikkinchi darajada paydo bo'ladi.",
                'kat': kat2,
            },
            {
                'savol': "Kimyoviy kuyishda nima qilish kerak?",
                'a': "Spirt surtish",
                'b': "Ko'p miqdorda oqar suv bilan yuvish",
                'c': "Muz qo'yish",
                'd': "Yog' surtish",
                'togri': 'b',
                'izoh': "Kimyoviy kuyishda kimyoviy moddani ko'p miqdorda oqar suv bilan yuvib tashlash kerak.",
                'kat': kat2,
            },
            {
                'savol': "Elektr toki urganida birinchi navbatda nima qilish kerak?",
                'a': "Jabrlanuvchini ushlab tortib olish",
                'b': "Tok manbasini o'chirish yoki izolatsiya qilingan narsa bilan ajratish",
                'c': "Suv quyish",
                'd': "Ko'tarib ko'chirish",
                'togri': 'b',
                'izoh': "Elektr toki urganida avval tok manbasini o'chirish yoki jabrlanuvchini izolatsiya qilingan narsa bilan elektr toki ta'siridan ajratish kerak.",
                'kat': None,
            },
            {
                'savol': "Qon ketayotgan jarohatda bintni qonga to'lsa nima qilish kerak?",
                'a': "Bintni olib yangi qo'yish",
                'b': "Jarohatni suv bilan yuvish",
                'c': "Ustiga yangi bint qo'yish, ostini olmay",
                'd': "Hech narsa qilmaslik",
                'togri': 'c',
                'izoh': "Bint qonga to'lsa, ostini olmay ustiga yangi qavat qo'yish kerak. Ostini olib tashlash qon laxtasini buzishi va qon ketishni kuchaytirishi mumkin.",
                'kat': kat1,
            },
            {
                'savol': "Arterial qon ketish qanday ko'rinadi?",
                'a': "To'q qizil rangda, sekin oqadi",
                'b': "Qoramtir rangda, tez oqadi",
                'c': "Yorqin qizil rangda, puls bilan otilib chiqadi",
                'd': "Sariq rangda oqadi",
                'togri': 'c',
                'izoh': "Arterial qon ketishda qon yorqin qizil bo'lib, yurak urishi bilan mos ravishda otilib chiqadi. Bu eng xavfli qon ketish turi.",
                'kat': kat1,
            },
            {
                'savol': "Burundan qon ketganda nima qilish kerak?",
                'a': "Boshni orqaga egish",
                'b': "Boshni oldinga egib, burunni 10 daqiqa chimchilash",
                'c': "Yotqizish",
                'd': "Issiq suv ichirish",
                'togri': 'b',
                'izoh': "Boshni oldinga egib, burun qanotlarini 10 daqiqa chimchilab turish kerak. Boshni orqaga egish qonni tomog'ga tushiradi.",
                'kat': kat1,
            },
            {
                'savol': "Diabet bemoriga qand (shakar) berish qachon to'g'ri?",
                'a': "Har doim",
                'b': "Hushsiz bo'lganda",
                'c': "Hushi joyida va gipoglikemiya alomatlari bo'lganda",
                'd': "Hech qachon",
                'togri': 'c',
                'izoh': "Diabetli bemorga faqat hushi joyida bo'lganda va qon shahari past bo'lgan belgilar ko'rinsa (titrash, terlash, ko'ngil aynish) qand berish mumkin.",
                'kat': None,
            },
            {
                'savol': "Insult (miya qon aylanishining buzilishi) alomati qanday aniqlanadi?",
                'a': "FAST: Yuz, Qo'l, Nutq, Telefon",
                'b': "Faqat bosh og'riq",
                'c': "Faqat ko'ngil aynish",
                'd': "Faqat qo'l uvishishi",
                'togri': 'a',
                'izoh': "FAST: Face (yuz qiyshayishi), Arm (qo'l kuchi yo'qligi), Speech (nutq buzilishi), Time (darhol 103 ga qo'ng'iroq).",
                'kat': None,
            },
            {
                'savol': "Yurak xurujida og'riq odatda qayerda seziladi?",
                'a': "Faqat qorin sohasida",
                'b': "Ko'krak sohasida, chap qo'lga va jag'ga tarqalishi mumkin",
                'c': "Faqat orqada",
                'd': "Faqat bosh sohasida",
                'togri': 'b',
                'izoh': "Yurak xurujida og'riq ko'krak sohasida seziladi va chap qo'l, jag', yelka va orqaga tarqalishi mumkin.",
                'kat': None,
            },
            {
                'savol': "Allergik reaksiyada (anafılaksiya) qanday dori ishlatiladi?",
                'a': "Aspirin",
                'b': "Paracetamol",
                'c': "Epinefrin (adrenalin)",
                'd': "Ibuprofen",
                'togri': 'c',
                'izoh': "Og'ir allergik reaksiya (anafilaksiya)da epinefrin (adrenalin) in'eksiyasi hayotni saqlab qoladi.",
                'kat': None,
            },
            {
                'savol': "Ko'z jarohatida nima qilish MUMKIN EMAS?",
                'a': "Ko'zni yopib qo'yish",
                'b': "Shifokorga murojaat qilish",
                'c': "Ko'zdagi yot jismni ishqalab olib tashlashga harakat qilish",
                'd': "Ko'zni yumshoq bint bilan bog'lash",
                'togri': 'c',
                'izoh': "Ko'zdagi yot jismni ishqalab olib tashlash ko'z soqqasiga zarar yetkazishi mumkin.",
                'kat': None,
            },
            {
                'savol': "Teri ostiga kirgan yot jismni (tikan, shisha) qanday olib tashlash kerak?",
                'a': "Ignani olovda sterilizatsiya qilib olib tashlash",
                'b': "Bosib siqib chiqarish",
                'c': "Shifokorga murojaat qilish",
                'd': "O'zi chiqib ketishini kutish",
                'togri': 'a',
                'izoh': "Yuzaki kirgan yot jismlarni sterilizatsiya qilingan igna yoki qisqich bilan ehtiyotlik bilan olib tashlash mumkin. Chuqur kirgan jismlar uchun shifokorga murojaat kerak.",
                'kat': None,
            },
            {
                'savol': "Harorat oshganida (isitma) birinchi yordam nima?",
                'a': "Issiq ko'rpa bilan yopish",
                'b': "Issiq ichimlik berish",
                'c': "Tana haroratini pasaytirish (dori, sovuq artish)",
                'd': "Isitma o'zi tushishini kutish",
                'togri': 'c',
                'izoh': "Isitmada tana haroratini dori yoki sovuq suv bilan artish orqali pasaytirish kerak. 38.5°C dan yuqori bo'lsa dori qabul qilish zarur.",
                'kat': None,
            },
            {
                'savol': "Bolaga sun'iy nafas berishda nafas kuchi qanday bo'lishi kerak?",
                'a': "Kattalar bilan bir xil",
                'b': "Kuchli va tez",
                'c': "Engil, faqat ko'krak ko'tarilguncha",
                'd': "Umuman sun'iy nafas bermaslik kerak",
                'togri': 'c',
                'izoh': "Bolaga sun'iy nafas berishda faqat ko'krak ko'tarilguncha engil nafas berish kerak. Kuchli nafas o'pkani shikastlashi mumkin.",
                'kat': kat3,
            },
            {
                'savol': "Chiqiqda (dislokatsiya) nima qilish kerak?",
                'a': "O'zingiz suyakni joyiga solish",
                'b': "Qimirlatmasdan shifokorga murojaat qilish",
                'c': "Issiq kompres qilish",
                'd': "Massaj qilish",
                'togri': 'b',
                'izoh': "Chiqiqda suyakni o'zingiz joyiga solishga HARAKAT QILMANG. Shifokor yordami kerak.",
                'kat': kat4,
            },
            {
                'savol': "Birinchi yordam ko'rsatishda aseptika nima degani?",
                'a': "Tez yordam chaqirish",
                'b': "Jarohatni infeksiyadan himoya qilish",
                'c': "Jarohatni yopish",
                'd': "Og'riqni qoldirish",
                'togri': 'b',
                'izoh': "Aseptika - jarohatga mikroblar kirishini oldini olish maqsadida amalga oshiriladigan chora-tadbirlar majmui.",
                'kat': None,
            },
            {
                'savol': "Jabrlanuvchini ko'chirishdan oldin nima tekshiriladi?",
                'a': "Yoshi",
                'b': "Umurtqa pog'onasi va bo'yin jarohatlanishi yo'qligi",
                'c': "Kiyimi",
                'd': "Pasporti",
                'togri': 'b',
                'izoh': "Jabrlanuvchini ko'chirishdan oldin umurtqa pog'onasi yoki bo'yin jarohatlanishini istisno qilish kerak, aks holda falajlik yuzaga kelishi mumkin.",
                'kat': None,
            },
            {
                'savol': "Tish og'rig'ida og'riqni vaqtincha qoldirish uchun nima qilsa bo'ladi?",
                'a': "Issiq suv bilan chayish",
                'b': "Og'riqsizlantiruvchi dori qabul qilish va tezda shifokorga borish",
                'c': "Sovuq suv bilan chayish",
                'd': "Spirt bilan artish",
                'togri': 'b',
                'izoh': "Og'riqsizlantiruvchi dori vaqtincha yordam beradi, ammo tish shifokoriga tezda murojaat qilish shart.",
                'kat': None,
            },
            {
                'savol': "Ilondan chaqqanda nima qilish kerak?",
                'a': "Zahrani og'iz bilan so'rib chiqarish",
                'b': "Chaqqan joyni kesish",
                'c': "Harakatni cheklash, jarohatni past holda ushlab 103 ga qo'ng'iroq qilish",
                'd': "Tez yurib kasalxonaga borish",
                'togri': 'c',
                'izoh': "Ilon chaqqanda harakatni cheklash (zahar tarqalishini sekinlashtiradi), jarohatni yurak darajasidan past ushlab, darhol tez yordam chaqirish kerak.",
                'kat': None,
            },
            {
                'savol': "Ari yoki ari chaqqanda tish (nish) qanday olib tashlanadi?",
                'a': "Qisqich bilan siqib",
                'b': "Karta yoki tirnoq bilan sidirib",
                'c': "Og'iz bilan so'rib",
                'd': "Hech narsa qilmaslik",
                'togri': 'b',
                'izoh': "Ari nishini karta yoki tirnoq bilan sidirib olib tashlash kerak. Qisqich bilan siqish zahar xaltachasini ezib, ko'proq zahar kiritadi.",
                'kat': None,
            },
            {
                'savol': "Quloqqa suv kirganida nima qilish kerak?",
                'a': "Paxta tiqish",
                'b': "Qulog'i pastga bo'lgan tomonga qiya yotib sakrash",
                'c': "Quloqqa isitilgan yog' quyish",
                'd': "Quloqni qattiq silkish",
                'togri': 'b',
                'izoh': "Quloqqa suv kirsa, u tomon pastga bo'ladigan holda tursangiz yoki bir oyoqda sakrasangiz suv o'z-o'zidan chiqishi mumkin.",
                'kat': None,
            },
            {
                'savol': "Shamollash va gripp farqi nimada?",
                'a': "Farqi yo'q",
                'b': "Gripp tez boshlanadi, yuqori isitma va tana og'rig'i bilan",
                'c': "Shamollash og'ir kechadi",
                'd': "Gripp faqat bolalarda bo'ladi",
                'togri': 'b',
                'izoh': "Gripp to'satdan boshlanadi, yuqori isitma (38-40°C), kuchli bosh og'riq va tana og'rig'i bilan kechadi. Shamollash asta-sekin rivojlanadi.",
                'kat': None,
            },
            {
                'savol': "Qorin sohasiga zarba yeganda qanday belgilar xavfli hisoblanadi?",
                'a': "Engil og'riq",
                'b': "Kuchli og'riq, qattiq qorin, qon aylanishning buzilishi",
                'c': "Ko'ngil aynish",
                'd': "Ishtaha yo'qolishi",
                'togri': 'b',
                'izoh': "Qorin sohasida kuchli og'riq, taxtasimon qattiq qorin va shok belgilari ichki qon ketish yoki a'zo shikastlanishini ko'rsatadi - darhol tez yordam kerak.",
                'kat': None,
            },
            {
                'savol': "Issiqlik urishi (teplovoy udar) belgilari qanday?",
                'a': "Sovuq ter, titroq",
                'b': "Yuqori tana harorati, quruq teri, chalkashlik",
                'c': "Past harorat, ko'k teri",
                'd': "Faqat bosh og'riq",
                'togri': 'b',
                'izoh': "Issiqlik urushida tana harorati oshadi (40°C gacha), teri qizaradi va quruq bo'ladi, odam chalkashan qoladi.",
                'kat': None,
            },
            {
                'savol': "Issiqlik urushida birinchi yordam nima?",
                'a': "Issiq o'rin-ko'rpaga o'rash",
                'b': "Sovuq joyga ko'chirish, kiyimini yechish, tanani sovutish",
                'c': "Issiq choy berish",
                'd': "Yugurish mashqi qilish",
                'togri': 'b',
                'izoh': "Issiqlik urushida soya va salqin joyga ko'chirish, kiyimlarni yechish, tana haroratini pasaytirish kerak.",
                'kat': None,
            },
            {
                'savol': "Sovuq urishi (muzlash, gipotermiya) darajalarida qaysi belgi xavfliligini ko'rsatadi?",
                'a': "Engil titroq",
                'b': "Titroq to'xtab, mudroqlik va chalkashlik boshlangani",
                'c': "Quloq og'rishi",
                'd': "Teridagi qizarish",
                'togri': 'b',
                'izoh': "Titroq to'xtashi - organizmning isitish mexanizmi ishlamayapti degan xavfli signal. Bu chuqur gipotermiyaning belgisi.",
                'kat': None,
            },
            {
                'savol': "Muzlagan oyoq-qo'lni qanday isitish kerak?",
                'a': "To'g'ridan-to'g'ri olovga yaqin tutish",
                'b': "Asta-sekin iliq suv bilan isitish (38-40°C)",
                'c': "Qor bilan ishqalash",
                'd': "Spirt surtish",
                'togri': 'b',
                'izoh': "Muzlagan joyni to'g'ridan-to'g'ri issiqlik manbalariga yaqin tutmaslik kerak - his yo'q bo'lganda kuyib ketishi mumkin. Iliq suv (38-40°C) bilan asta isitish to'g'ri.",
                'kat': None,
            },
            {
                'savol': "Suv ostida cho'kish xavfidan qutqarilgan odamga birinchi yordam nima?",
                'a': "Ko'tarib uzoqlash",
                'b': "Nafas yo'llarini tozalab YOR boshlash (kerak bo'lsa)",
                'c': "Issiq choy berish",
                'd': "Karovatga yotqizish",
                'togri': 'b',
                'izoh': "Cho'kishdan qutqarilganda nafas yo'llarini tozalab, nafas va yurak urishi tekshiriladi. Kerak bo'lsa yurak-o'pka resusitatsiyasi boshlanadi.",
                'kat': kat3,
            },
            {
                'savol': "Jarohat bo'lganda tetanus (qoqshol) xavfi qachon yuqori?",
                'a': "Toza jarohatda",
                'b': "Tuproq, metal yoki hayvon teggan chuqur jarohatda",
                'c': "Faqat katta jarohatda",
                'd': "Faqat bolalarda",
                'togri': 'b',
                'izoh': "Tuproq, zang bosgan metal yoki hayvon tishlaganda tetanus xavfi yuqori bo'ladi. Bunday holatlarda shifokorga murojaat va emlash zarur.",
                'kat': kat1,
            },
            {
                'savol': "Birinchi yordam ko'rsatganda nima uchun qo'lqop kiyish kerak?",
                'a': "Qo'l sovumasligi uchun",
                'b': "Jabrlanuvchidan infeksiya olmaslik va unga bermaslik uchun",
                'c': "Qo'lni ifloslantirmaslik uchun",
                'd': "Bu talab emas",
                'togri': 'b',
                'izoh': "Qo'lqop kiyish ikki tomonlama himoya qiladi: sizni jabrlanuvchining qonidan, jabrlanuvchini esa sizning mikroblaringizdan saqlaydi.",
                'kat': kat1,
            },
            {
                'savol': "Tez yordam ko'rsatishda jabrlanuvchi hushsiz bo'lsa telefon qo'yishda nima aytish kerak?",
                'a': "Faqat ismini aytish",
                'b': "Aniq manzil, holat tavsifi va qo'ng'iroqchi telefon raqamini aytish",
                'c': "Faqat telefon raqamini aytish",
                'd': "Hech narsa aytmasdan kutish",
                'togri': 'b',
                'izoh': "Tez yordamga qo'ng'iroq qilganda aniq manzil, jabrlanuvchining holati va o'zingizning telefon raqamingizni aytish kerak.",
                'kat': None,
            },
            {
                'savol': "Bolada febrile (isitmalik) tutqanoq bo'lganda nima qilish kerak?",
                'a': "Tishlarini ochib narsa tiqish",
                'b': "Bolani mahkam ushlab olish",
                'c': "Xavfsiz joyga yotqizib boshni yon tomonga burish, 103 ga qo'ng'iroq qilish",
                'd': "Og'ziga suv quyish",
                'togri': 'c',
                'izoh': "Tutqanoqda bolani xavfsiz joyga yotqizib, boshini yon tomonga burib, 103 ga qo'ng'iroq qilish kerak. Mahkam ushlamang va og'ziga narsa tiqmang.",
                'kat': None,
            },
            {
                'savol': "Birinchi yordam ko'rsatishdan oldin o'zingizni xavfsizligini ta'minlash nima uchun muhim?",
                'a': "Bu muhim emas",
                'b': "Ikkala odam ham zararlanib qolmaslik uchun",
                'c': "Vaqtni tejash uchun",
                'd': "Faqat qonun talab qilgani uchun",
                'togri': 'b',
                'izoh': "O'z xavfsizligingizni ta'minlamasdan yordam bersangiz, ikkinchi jabrlanuvchiga aylanib qolishingiz mumkin va bu yordam berish imkonini kamaytiradi.",
                'kat': None,
            },
            {
                'savol': "Yarador bo'yin umurtqasi shubhasi bo'lganda boshni qanday ushlab turish kerak?",
                'a': "Boshni tez burish",
                'b': "Boshni neytral holatda qimirlatmasdan ushlab turish",
                'c': "Oldinga engashtirish",
                'd': "Orqaga egish",
                'togri': 'b',
                'izoh': "Bo'yin umurtqasi shikastlanganda boshni har qanday harakat qilish falajlikka olib kelishi mumkin. Neytral holatda qimirlatmasdan ushlab turish kerak.",
                'kat': None,
            },
            {
                'savol': "Qo'l suyagi singanda shina (mahkamlovchi) qayerga bog'lanadi?",
                'a': "Faqat singan joyga",
                'b': "Singan joyning ikki tomonidagi bo'g'inlarni ham qamrab olgan holda",
                'c': "Faqat bilakka",
                'd': "Faqat yelkaga",
                'togri': 'b',
                'izoh': "Shina singan joyning ikkala tomonidagi bo'g'inlarni ham qamrab olishi kerak. Bu singan joyni barqaror holatda saqlaydi.",
                'kat': kat4,
            },
            {
                'savol': "Ko'krak suyagi singanda nima qilish MUMKIN EMAS?",
                'a': "Shifokorga murojaat qilish",
                'b': "Mahkam bog'lash",
                'c': "Og'riqsizlantiruvchi berish",
                'd': "Qimirlatmaslik",
                'togri': 'b',
                'izoh': "Ko'krak suyagi singanda mahkam bog'lash nafas olishni qiyinlashtiradi. Shifokor ko'rigisiz hech narsa qilmaslik kerak.",
                'kat': kat4,
            },
            {
                'savol': "Og'ir shikastlanishda shok belgilari qanday?",
                'a': "Yuqori qon bosimi, sekin yurak urishi",
                'b': "Past qon bosimi, tez va zaiflashgan yurak urishi, sovuq ter, rangparlik",
                'c': "Normal holat",
                'd': "Faqat bosh og'riq",
                'togri': 'b',
                'izoh': "Shokda qon bosimi tushadi, yurak tez va zaif uradi, teri sovuq va terib, rang o'chadi. Bu hayot uchun xavfli holat.",
                'kat': None,
            },
            {
                'savol': "Shok holatida jabrlanuvchining oyoqlarini qanday qilish kerak?",
                'a': "Pastga tushirish",
                'b': "Yuqori ko'tarish (agar umurtqa shikastlanmagan bo'lsa)",
                'c': "Bukish",
                'd': "Hech narsa qilmaslik",
                'togri': 'b',
                'izoh': "Shokda oyoqlarni 30 sm ga ko'tarish miyaga qon oqimini yaxshilaydi (agar umurtqa shikastlanishi shubhasi bo'lmasa).",
                'kat': None,
            },
            {
                'savol': "Nafas yo'li berkitilganda (bo'g'ilish) bolaga (1 yoshdan katta) Geymlix usulini qanday bajarish kerak?",
                'a': "Ko'krakni bosish",
                'b': "Orqasidan quchoqlab qorin sohasiga yuqoriga qarab bosish",
                'c': "Boshini pastga egib orqasidan urish",
                'd': "Ko'tarib silkash",
                'togri': 'b',
                'izoh': "1 yoshdan katta bolalarda va kattalarda Geymlix usuli: orqasidan quchoqlab, qorin sohasiga yuqoriga qarab qisqa va kuchli bosishlar qilinadi.",
                'kat': kat6,
            },
            {
                'savol': "1 yoshgacha chaqaloqda bo'g'ilishda nima qilish kerak?",
                'a': "Katta odam kabi Geymlix usuli",
                'b': "Yuzini pastga qilib 5 ta orqa urish, keyin 5 ta ko'krak bosishi",
                'c': "Qorinni bosish",
                'd': "Faqat yig'latish",
                'togri': 'b',
                'izoh': "Chaqaloqlarda (1 yoshgacha) nafas yo'li berkitilganda: yuzini pastga tutib 5 ta orqa urish, keyin 5 ta ko'krak bosishi alternatsiyasi qo'llaniladi.",
                'kat': kat6,
            },
            {
                'savol': "Kuyish paytida yopishgan kiyimni nima qilish kerak?",
                'a': "Kuch bilan yulib olish",
                'b': "Teriga yopishgan kiyimni kesib atrofini qoldirish",
                'c': "Issiq suv quyib yumshatish",
                'd': "Yog' surtib ajratish",
                'togri': 'b',
                'izoh': "Teriga yopishgan kiyimni kuch bilan yulib olish terini yanada shikastlaydi. Atrofini qirqib, yopishgan qismni joyida qoldirish kerak.",
                'kat': kat2,
            },
            {
                'savol': "Ko'z kimyoviy zaharlanishida nima qilish kerak?",
                'a': "Ko'zni ishqalash",
                'b': "Ko'zni 15-20 daqiqa ko'p miqdorda oqar suv bilan yuvish",
                'c': "Ko'zni yopiq ushlab shifokorga borish",
                'd': "Ko'zga dori damchisi tomizish",
                'togri': 'b',
                'izoh': "Kimyoviy modda ko'zga tushganda darhol 15-20 daqiqa ko'p miqdorda oqar suv bilan yuvish kerak.",
                'kat': None,
            },
            {
                'savol': "Jabrlanuvchini sahnadan ko'chirish qachon zarur?",
                'a': "Har doim",
                'b': "Faqat xavf davom etayotganda",
                'c': "Hech qachon",
                'd': "Shifokor kelgunga qadar",
                'togri': 'b',
                'izoh': "Jabrlanuvchini xavfsiz bo'lmasa ko'chirish kerak. Aks holda, ularni joy-joyida saqlab, yordam ko'rsatish afzalroq.",
                'kat': None,
            },
            {
                'savol': "Yonma-yon jarohatda (ko'krak ochiq jarohat) nima qilish kerak?",
                'a': "Qalin bint bilan mahkam bog'lash",
                'b': "Uch tomondan yopiq, bir tomoni ochiq (ventil) bog'lam qo'yish",
                'c': "Ochiq qoldirish",
                'd': "Suv quyish",
                'togri': 'b',
                'izoh': "Ko'krakda ochiq yarada uch tarafdan yopiq, bir tarafdan ochiq qilib yopish kerak - bu havoning kirmasligini ta'minlab, ortiqcha bosimning chiqishiga yo'l qo'yadi.",
                'kat': None,
            },
            {
                'savol': "Tizza bo'g'imi shikastlanishida birinchi yordam nima?",
                'a': "Bukish va to'g'rilash",
                'b': "Qimirlatmaslik, muzlatish va shifokorga murojaat",
                'c': "Issiq kompres",
                'd': "Massaj qilish",
                'togri': 'b',
                'izoh': "Bo'g'im shikastlanishida qimirlatmasdan muzlatish (20 daqiqa, har soatda) va shifokorga murojaat kerak.",
                'kat': kat4,
            },
            {
                'savol': "Oyoq mushagiga tortishma (kramp) bo'lganda nima qilish kerak?",
                'a': "Issiq suv quyish",
                'b': "Oyoqni bukib va barmoqni o'ziga qarab tortish",
                'c': "Ko'tarib silkash",
                'd': "Uqalash va isitish",
                'togri': 'b',
                'izoh': "Oyoq krampida oyoqni to'g'rilab, barmoqlarni o'zingizga qarab torting. Bu mushakni cho'zib, krampni to'xtatadi.",
                'kat': None,
            },
            {
                'savol': "Bolaning burniga yoki qulog'iga yot jism kirsa nima qilish kerak?",
                'a': "O'zingiz qo'llab olib tashlash",
                'b': "Puf etib chiqarish",
                'c': "Shifokorga murojaat qilish",
                'd': "Suv quyib chiqarish",
                'togri': 'c',
                'izoh': "Yot jismni o'zingiz olib tahlashga urinish uni yanada chuqurroq itarishi mumkin. Shifokor yordami tavsiya etiladi.",
                'kat': None,
            },
            {
                'savol': "Ko'z chiqib ketishida (luxatsiya) nima qilish MUMKIN EMAS?",
                'a': "Toza bint bilan yopish",
                'b': "Shifokorga murojaat qilish",
                'c': "Ko'zni uqalash yoki ichiga solishga urinish",
                'd': "Ko'zga bosim bermaslik",
                'togri': 'c',
                'izoh': "Ko'z chiqib ketishida ASLO uqalash yoki ichiga solishga urinmang. Toza steril bint bilan yopib tezda shifokorga boring.",
                'kat': None,
            },
            {
                'savol': "Qorin bo'shlig'idagi a'zolar chiqib ketsa (eventeratsiya) nima qilish kerak?",
                'a': "A'zolarni ichiga itarish",
                'b': "Nam steril bint bilan yopib 103 ga qo'ng'iroq qilish",
                'c': "Quruq mato bilan mahkam bog'lash",
                'd': "Suv bilan yuvish",
                'togri': 'b',
                'izoh': "Chiqib ketgan a'zolarni ichiga solishga urinmang. Ularni nam steril bint bilan yopib, darhol tez yordam chaqiring.",
                'kat': None,
            },
            {
                'savol': "Yurak xurujida aspirin berish qachon foydali?",
                'a': "Hech qachon",
                'b': "Faqat allergiyasi bo'lmasa va doktor tavsiya qilsa",
                'c': "Har doim",
                'd': "Faqat bolalarga",
                'togri': 'b',
                'izoh': "Yurak xurujida aspirin qonni suyultirib foydali bo'lishi mumkin, lekin allergiya yoki qarama-qarshi ko'rsatmalar bo'lmasa va tibbiy maslahat asosida beriladi.",
                'kat': None,
            },
            {
                'savol': "Nafas olishni o'z nazoratimizda oson bajarish mumkin, lekin quyidagilardan qaysi biri to'g'ri?",
                'a': "Nafas olish har doim ixtiyoriy",
                'b': "Nafas olish ham ixtiyoriy, ham ixtiyorsiz (reflektor) bo'lishi mumkin",
                'c': "Nafas olish faqat ixtiyorsiz",
                'd': "Nafas olishni to'la nazorat qilib bo'lmaydi",
                'togri': 'b',
                'izoh': "Nafas olish ham ixtiyoriy (ongli boshqarish) ham ixtiyorsiz (avtomat) tarzda amalga oshiriladi.",
                'kat': None,
            },
            {
                'savol': "Qon bosimi pasayishida (gipotenziya) birinchi yordam nima?",
                'a': "Tik turgizish",
                'b': "Oyoqlarini ko'targan holda yotqizish",
                'c': "Yugurishga majbur qilish",
                'd': "Sovuq suv ichirish",
                'togri': 'b',
                'izoh': "Qon bosimi tushganda oyoqlarni ko'tarish miyaga qon oqimini yaxshilaydi.",
                'kat': None,
            },
            {
                'savol': "Qon bosimi ko'tarilganda (gipertenziv kriz) birinchi yordam nima?",
                'a': "Yugurish",
                'b': "Dam olish, vaziyatni tinchitish va shifokorga murojaat",
                'c': "Sovuq suv ichirish",
                'd': "Issiq vanna qabul qilish",
                'togri': 'b',
                'izoh': "Gipertenziv krizda tinchlanish, yotish va darhol tibbiy yordam chaqirish kerak.",
                'kat': None,
            },
            {
                'savol': "Astma xurujida birinchi yordam nima?",
                'a': "Yotqizish",
                'b': "O'tirqizish, ingalyatordan foydalanish, toza havo",
                'c': "Yugurishga majbur qilish",
                'd': "Suv ichirish",
                'togri': 'b',
                'izoh': "Astma xurujida bemor o'tirib, ingalyatordan foydalanib, toza havo olishi kerak. Nafas olish qiyinlashsa 103 ga qo'ng'iroq qilish zarur.",
                'kat': None,
            },
            {
                'savol': "Aqliy stressda (panik ataka) birinchi yordam nima?",
                'a': "Tashlab ketish",
                'b': "Sekin nafas olishga o'rgatish va tinch ovoz bilan gaplashish",
                'c': "Suv sepish",
                'd': "Qichqirish",
                'togri': 'b',
                'izoh': "Panik atakada shaxsni xotirjam qilish, sekin chuqur nafas olishga yo'naltirish va tinch ovoz bilan gaplashish yordam beradi.",
                'kat': None,
            },
            {
                'savol': "Ko'krak qafasi siqilishi (qovurg'a sinishi) shubhasi bo'lganda qanday nafas olish kerak?",
                'a': "Kuchli va tez",
                'b': "Yuzaki va sekin",
                'c': "Nafasni to'xtatish",
                'd': "Og'izdan nafas",
                'togri': 'b',
                'izoh': "Qovurg'a singanda chuqur nafas og'riqli bo'ladi. Yuzaki nafas olish og'riqni kamaytiradi lekin shifokor ko'rigi zarur.",
                'kat': kat4,
            },
            {
                'savol': "Qand diabeti bo'lgan odamda gipoglikemiya (qon shakari pastligi) belgilari qanday?",
                'a': "Chanqoqlik, tez-tez siyish",
                'b': "Titrash, ter bosish, chalkashlik, zaiflik",
                'c': "Ko'z qorachig'i torayishi",
                'd': "Teri qorayishi",
                'togri': 'b',
                'izoh': "Gipoglikemiya belgilari: titrash, ko'p terlash, zaiflik, chalkashlik, ba'zan hushdan ketish.",
                'kat': None,
            },
            {
                'savol': "Qand diabetida hushsiz bemor bo'lsa nima qilish kerak?",
                'a': "Og'ziga shakar berish",
                'b': "103 ga qo'ng'iroq qilish, yon holatga yotqizish",
                'c': "Insulin yuboring",
                'd': "Suv ichirish",
                'togri': 'b',
                'izoh': "Hushsiz bemorga og'iz orqali hech narsa bermaslik kerak - bo'g'ilib qolishi mumkin. Darhol tez yordam chaqiring.",
                'kat': None,
            },
            {
                'savol': "Urinish jarohatida (zarbdan) birinchi yordam nima?",
                'a': "Issiq kompres",
                'b': "Sovuq kompres (muz yoki sovuq suv)",
                'c': "Massaj qilish",
                'd': "Isitish",
                'togri': 'b',
                'izoh': "Urinish jarohatida (bruise) sovuq kompres shishni va og'riqni kamaytiradi. Dastlabki 24-48 soatda issiqlikdan saqlaning.",
                'kat': None,
            },
            {
                'savol': "Birinchi yordam ko'rsatishda «imkon qadar tezroq» tamoyili nimani anglatadi?",
                'a': "Tez yugurish",
                'b': "Hayot uchun xavfli holatlarni boshqalarga qaraganda oldin hal qilish",
                'c': "Ko'p narsa qilish",
                'd': "Tez gapirishni",
                'togri': 'b',
                'izoh': "Hayot uchun xavfli holatlar (nafas to'xtashi, kuchli qon ketish) boshqalardan oldin hal qilinishi kerak.",
                'kat': None,
            },
            {
                'savol': "Quruq ko'z sindromida nima qilish mumkin?",
                'a': "Ko'zni ishqalash",
                'b': "Sun'iy ko'z yoshi damchilari qo'yish va ko'z shifokoriga murojaat",
                'c': "Suv bilan yuvish",
                'd': "Ko'zni yopiq saqlash",
                'togri': 'b',
                'izoh': "Quruq ko'z sindromida sun'iy ko'z yoshi preparatlari yordam beradi, ammo sababi aniqlash uchun ko'z shifokoriga murojaat zarur.",
                'kat': None,
            },
            {
                'savol': "Tunda yo'lda avariya bo'lganda birinchi nima qilish kerak?",
                'a': "Jabrlanuvchilarga qarab yugurish",
                'b': "Xavfsizlikni ta'minlash (ogohlantiruvchi belgilar qo'yish, yorug'lik yoqish) keyin yordam",
                'c': "Darhol jabrlanuvchilarni ko'chirish",
                'd': "Faqat telefon qilish",
                'togri': 'b',
                'izoh': "Avval o'zingiz va boshqalar xavfsizligini ta'minlang, ogohlantiruvchi uchburchak qo'ying, keyin yordam ko'rsating.",
                'kat': None,
            },
            {
                'savol': "Itdan tishlanganda nima qilish kerak?",
                'a': "Faqat bint bog'lash",
                'b': "Jarohatni sovunli suv bilan yuvish, shifokorga murojaat qilish",
                'c': "Yod surtib tashlash",
                'd': "Hech narsa qilmaslik",
                'togri': 'b',
                'izoh': "It tishlaganda quturish xavfi bor. Jarohatni 15 daqiqa sovunli suv bilan yuvib, shifokorga murojaat qilish zarur.",
                'kat': None,
            },
            {
                'savol': "Qattiq zarba natijasida bosh miyaga shikastlanish (konkussiya) belgilari qanday?",
                'a': "Faqat bosh og'riq",
                'b': "Hushdan ketish, ko'ngil aynish/qayt qilish, amneziya, bosh og'riq",
                'c': "Faqat quloq og'riq",
                'd': "Faqat ko'z og'riq",
                'togri': 'b',
                'izoh': "Konkussiyada hushdan ketish (yoki esxonasi ketish), ko'ngil aynish, qayt qilish, hodisani eslay olmaslik kuzatiladi.",
                'kat': None,
            },
            {
                'savol': "Og'ir bosh miya jarohatlanganda (koma) birinchi yordam nima?",
                'a': "Suv ichirish",
                'b': "Yon holatga yotqizib nafas yo'lini ochiq ushlab, 103 ga qo'ng'iroq qilish",
                'c': "Boshini ko'tarish",
                'd': "Tebratish",
                'togri': 'b',
                'izoh': "Komada nafas yo'lini ochiq saqlash (yon holat) va darhol tez yordam chaqirish asosiy choralar hisoblanadi.",
                'kat': kat3,
            },
            {
                'savol': "Birinchi yordam to'plami (aptechka) da qanday dori bo'lmaydi?",
                'a': "Aspirin",
                'b': "Bint",
                'c': "Antidepressant",
                'd': "Yod",
                'togri': 'c',
                'izoh': "Birinchi yordam aptechkasida antidepressantlar saqlanmaydi. U uchun shifokor buyruqnomasi zarur.",
                'kat': None,
            },
            {
                'savol': "Suv bilan bo'kib qolgan yog'och bilan urilganda qanday jarohat bo'lishi mumkin?",
                'a': "Faqat tashqi jarohat",
                'b': "Ichki qon ketish va yashirin shikastlanishlar",
                'c': "Faqat sinish",
                'd': "Faqat chiqiq",
                'togri': 'b',
                'izoh': "Katta kuch bilan urilganda ichki a'zolar shikastlanishi va ichki qon ketish bo'lishi mumkin - tashqaridan ko'rinmasa ham.",
                'kat': None,
            },
            {
                'savol': "Ko'z atrofidagi mayda shisha siniqlari uchun birinchi yordam nima?",
                'a': "Ko'zni yuvish",
                'b': "Ko'zni ishqalash",
                'c': "Ko'zni yopmay darhol shifokorga murojaat",
                'd': "Ko'zga moy damchilari tomizish",
                'togri': 'c',
                'izoh': "Mayda shisha siniqlari ko'z pardasini teshib o'tishi mumkin. Ko'zni yuvish yoki ishqalash kerak emas - darhol ko'z shifokoriga boring.",
                'kat': None,
            },
            {
                'savol': "Havoning issiqligida yurish paytida qanday belgilar issiqlik urishi xavfini bildiradi?",
                'a': "Chanqoqlik",
                'b': "Bosh aylanishi, ko'ngil aynish, terining to'xtashi",
                'c': "Ishtaha ochilishi",
                'd': "Uyquchanlik",
                'togri': 'b',
                'izoh': "Issiqlik urishi oldidan bosh aylanishi, ko'ngil aynish va terining to'xtashi (issiqlikni chiqara olmaslik) kuzatiladi.",
                'kat': None,
            },
            {
                'savol': "Ko'krak siqilishi yoki nafas qiyinlashuvida jismoniy faoliyat qilish kerakmi?",
                'a': "Ha, yugurish yordam beradi",
                'b': "Yo'q, to'xtatib tinchlanish va yordam chaqirish kerak",
                'c': "Yengil yurish foydali",
                'd': "Bir nechta sakrash kerak",
                'togri': 'b',
                'izoh': "Ko'krak siqilishi yoki nafas qiyinlashuvida jismoniy faoliyat yurak yukini oshirib holatni yomonlashtiradi. To'xtatib, tinchlanib yordam chaqirish kerak.",
                'kat': None,
            },
            {
                'savol': "Yong'inda tutun ichida qolinsangiz qanday harakat qilish kerak?",
                'a': "To'g'ri turib yugurish",
                'b': "Egilgan holda harakat qilish (tutun yuqorida to'planadi)",
                'c': "O'tirib kutish",
                'd': "Eshikni ochib o'tirish",
                'togri': 'b',
                'izoh': "Tutun yuqorida to'planadi. Egilib yoki emaklab harakat qilsangiz, toza havo quyi qismda bo'ladi.",
                'kat': None,
            },
            {
                'savol': "Qovurg'a sinishi shubhasida shifokor kelgunga qadar qanday holat qabul qilish kerak?",
                'a': "Yotib olish",
                'b': "O'tirish yoki yarim o'tirishda bo'lish",
                'c': "Tik turish",
                'd': "Yurish",
                'togri': 'b',
                'izoh': "Qovurg'a singanda o'tirish yoki yarim yotish nafas olishni osonlashtiradi.",
                'kat': kat4,
            },
            {
                'savol': "Yelkasi chiqib ketgan odamga birinchi yordam nima?",
                'a': "Yelkani joyiga solish",
                'b': "Qo'lni ehtiyotlik bilan mahkamlab shifokorga olib borish",
                'c': "Yelkani issiq suv bilan isitish",
                'd': "Massaj qilish",
                'togri': 'b',
                'izoh': "Yelka chiqiqida o'zingiz joyiga solishga urinmang. Qo'lni ehtiyotlik bilan mahkamlab, shifokorga olib boring.",
                'kat': kat4,
            },
            {
                'savol': "Qor ko'chirishda (lavina) ko'milgan odamni topganda nima qilish kerak?",
                'a': "Tez tortib chiqarish",
                'b': "Nafas yo'llarini tozalab, ehtiyotlik bilan qazib chiqarish",
                'c': "Qoldirib ketish",
                'd': "Ustiga ko'proq qor yopish",
                'togri': 'b',
                'izoh': "Lavina ostidan chiqarish jarayonida nafas yo'llarini tozalash va ehtiyotlik bilan harakat qilish muhim.",
                'kat': None,
            },
            {
                'savol': "O't o'chirish bo'linmasi telefon raqami necha?",
                'a': "101",
                'b': "102",
                'c': "103",
                'd': "104",
                'togri': 'a',
                'izoh': "O't o'chirish bo'linmasi - 101. 102 - militsiya, 103 - tez yordam, 104 - gaz xizmati.",
                'kat': None,
            },
            {
                'savol': "Militsiya telefon raqami necha?",
                'a': "101",
                'b': "102",
                'c': "103",
                'd': "104",
                'togri': 'b',
                'izoh': "Militsiya - 102. 101 - o't o'chirish, 103 - tez yordam, 104 - gaz xizmati.",
                'kat': None,
            },
            {
                'savol': "Gaz sizishi sezilsa nima qilish kerak?",
                'a': "Elektr chiroqni yoqish",
                'b': "Deraza va eshiklarni ochib xonani shamollatish, 104 ga qo'ng'iroq qilish",
                'c': "Uyda qolish",
                'd': "Gugurt yoqish",
                'togri': 'b',
                'izoh': "Gaz sizishida hech qanday elektr asbobni ishlatmaslik, deraza-eshiklarni ochib xonani shamollatish va 104 ga qo'ng'iroq qilish kerak.",
                'kat': None,
            },
            {
                'savol': "YOR (CPR) ning to'liq nomi nima?",
                'a': "Yurak-O'pka Resusitatsiyasi",
                'b': "Yuqori-Og'ir Reanimatsiya",
                'c': "Yashil-O'simlik Reabilitatsiya",
                'd': "Yumshoq-Og'riqsiz Reaksiya",
                'togri': 'a',
                'izoh': "YOR - Yurak-O'pka Resusitatsiyasi (CPR - Cardiopulmonary Resuscitation). Bu yurak to'xtashida bajariladigan hayot saqlovchi usul.",
                'kat': kat3,
            },
            {
                'savol': "Yemirilgan binosidan qochish imkoni bo'lmasa qanday harakat qilish kerak?",
                'a': "Devor yoniga o'tirish",
                'b': "Kuchli konstruktsiya (jadval, tokcha) yonida to'planib signal berish",
                'c': "Eshikka chiqishga urinish",
                'd': "Derazadan sakrash",
                'togri': 'b',
                'izoh': "Binoda qolib ketsangiz, kuchli konstruktsiyalar yonida to'planing, qimirlamang va qutqaruvchilarga signal (qichqirish, narsaga urib signal berish) bering.",
                'kat': None,
            },
            {
                'savol': "Teri ostiga havo kirishi (emfizema) qanday belgi beradi?",
                'a': "Terining qizarishi",
                'b': "Bosganida g'ichirlash sezilishi",
                'c': "Terining ko'karishi",
                'd': "Harorat ko'tarilishi",
                'togri': 'b',
                'izoh': "Teri ostiga havo kirganda bosganida g'ichirlash (kreptatsiya) seziladi. Bu jiddiy jarohatlarda bo'ladi.",
                'kat': None,
            },
            {
                'savol': "Tez yordam xizmati qo'ng'iroqni qabul qilganda ular nima so'raydi?",
                'a': "Faqat ismingizni",
                'b': "Aniq manzil, holat tavsifi, jabrlanuvchilar soni, qo'ng'iroqchi telefoni",
                'c': "Faqat telefon raqamni",
                'd': "Pasport ma'lumotlarini",
                'togri': 'b',
                'izoh': "Tez yordam dispetcheri aniq manzil, holat tavsifi, nechta odam, eng og'iri haqida va qo'ng'iroqchi telefon raqamini so'raydi.",
                'kat': None,
            },
            {
                'savol': "Shikastlangandan so'ng jabrlanuvchi yig'lasasa nima anglatadi?",
                'a': "Ahvoli yomon",
                'b': "Hushi joyida va nafas olayapti",
                'c': "Og'riq yo'q",
                'd': "Ko'mak kerak emas",
                'togri': 'b',
                'izoh': "Yig'lash uchun nafas kerak va bu hushini bildiradigan belgi. Demak jabrlanuvchi nafas olayapti va hushi joyida.",
                'kat': kat3,
            },
            {
                'savol': "Qovurg'a sinishini suyak sinishidan qanday farqlash mumkin?",
                'a': "Farqlash mumkin emas",
                'b': "Nafas olishda og'riq, qovurg'a sohasida bosganida og'riq",
                'c': "Faqat ko'karish",
                'd': "Faqat shish",
                'togri': 'b',
                'izoh': "Qovurg'a sinishida nafas olish va yo'talganda og'riq keskin kuchayadi, singan joy bosganida og'riq seziladi.",
                'kat': kat4,
            },
            {
                'savol': "Teri ko'karishida (gematoma) dastlabki soatda nima qilish kerak?",
                'a': "Issiq kompres",
                'b': "Sovuq kompres 20 daqiqa, keyin tanaffus",
                'c': "Massaj",
                'd': "Hech narsa qilmaslik",
                'togri': 'b',
                'izoh': "Ko'karishda dastlabki 24-48 soatda sovuq kompres (20 daqiqa qo'yib, 20 daqiqa olish) shishni va og'riqni kamaytiradi.",
                'kat': None,
            },
            {
                'savol': "Birinchi yordam ko'rsatishda asosiy tamoyil qaysi?",
                'a': "Iloji boricha ko'proq narsa qilish",
                'b': "Avval zarar yetkazmaslik (Primum non nocere)",
                'c': "Tez ko'chirish",
                'd': "Shifokor kelgunga qadar kutish",
                'togri': 'b',
                'izoh': "Birinchi yordamning asosiy tamoyili - avval zarar yetkazmaslik. Noto'g'ri harakatlar holatni yomonlashtirishi mumkin.",
                'kat': None,
            },
            {
                'savol': "Favqulodda vaziyatlar xizmati telefon raqami necha?",
                'a': "101",
                'b': "102",
                'c': "103",
                'd': "1050",
                'togri': 'd',
                'izoh': "Favqulodda vaziyatlar vazirligi - 1050. 101 - o't o'chirish, 102 - militsiya, 103 - tez yordam.",
                'kat': None,
            },
        ]

        for s in savollar:
            TestSavol.objects.get_or_create(
                savol=s['savol'],
                defaults={
                    'variant_a': s['a'], 'variant_b': s['b'],
                    'variant_c': s['c'], 'variant_d': s['d'],
                    'togri_javob': s['togri'], 'izoh': s['izoh'],
                    'kategoriya': s['kat'],
                }
            )
        self.stdout.write(self.style.SUCCESS("Test savollari yuklandi"))

        # ===== BOLALAR BO'LIMI =====

        # Ogohlantirishlar
        ogohlantirishlar = [
            ("Nafas yo'li berkitilganda darhol 103 ga qo'ng'iroq qiling", 1),
            ("Bolaga dori berishdan oldin shifokorga maslahatlashing", 2),
            ("Bola hushsiz bo'lsa og'ziga hech narsa bermang", 3),
            ("Kuygan joyga yog', tish pastasi yoki krem surtmang", 4),
            ("Bolada tutqanoq bo'lsa tishiga narsa tiqmang", 5),
            ("1 yoshgacha chaqaloqqa Geymlik usulini qo'llamang", 6),
        ]
        for matn, tartib in ogohlantirishlar:
            BolalarOgohlantirish.objects.get_or_create(
                matn=matn, defaults={'tartib': tartib}
            )

        # Foydali ma'lumotlar
        malumotlar_data = [
            ("🌡️", "Isitma", "Bolada 38°C dan yuqori harorat bo'lsa, paracetamol yoki ibuprofen bering. Sovuq arting. 39°C dan yuqori bo'lsa shifokor chaqiring.", "#ef4444", 1),
            ("🩹", "Jarohat", "Kichik jarohatni sovunli suv bilan yuving. Steril bint yoki plastir qo'ying. Chuqur yaralarda darhol shifokorga murojaat qiling.", "#f59e0b", 2),
            ("🤧", "Shamollash", "Ko'p suyuqlik bering, dam oldiring. Burun tomchilari va vitamin C yordam beradi. 3 kundan ortiq davom etsa shifokorga boring.", "#3b82f6", 3),
            ("🤮", "Qayt qilish", "Suyuqlik yo'qolishining oldini olish uchun kichik yutumlarda suv bering. 24 soatdan ortiq davom etsa shifokorga murojaat qiling.", "#8b5cf6", 4),
            ("🐝", "Hayvon chaqishi", "Ari nishini sidirib oling. Joy bilan sovuq kompres qo'ying. Allergiya belgilari (nafas qiynalishi, shishish) bo'lsa darhol 103 ga qo'ng'iroq qiling.", "#16a34a", 5),
            ("💊", "Dori xavfsizligi", "Dorilarni bolalar ko'zi yetmaydigan joyda saqlang. Muddati o'tgan dorilarni tozalang. Hech qachon kattalarga mo'ljallangan dozada bermang.", "#dc2626", 6),
        ]
        for icon, sarlavha, matn, rang, tartib in malumotlar_data:
            BolalarMalumot.objects.get_or_create(
                sarlavha=sarlavha,
                defaults={'icon': icon, 'matn': matn, 'rang': rang, 'tartib': tartib}
            )

        # Bolalar mavzulari
        mavzular_data = [
            {
                'sarlavha': "Chaqaloqda bo'g'ilish",
                'tavsif': "1 yoshgacha chaqaloqqa narsa tiqilib qolsa qanday harakat qilish kerak. Bu eng xavfli holatlardan biri bo'lib, to'g'ri usulni bilish hayot saqlab qoladi.",
                'icon': '👶',
                'tartib': 1,
                'tanlangan': True,
                'qadamlar': [
                    "Chaqaloqni yuzini pastga qilib bilagingizdagi qo'lingizda ushlab oling.",
                    "Kurak suyaklari orasiga kafting pastki qismi bilan 5 marta qattiq uring.",
                    "Chalqancha agdarib, ko'krakka 2 barmoq bilan 5 marta bosing.",
                    "Ob'ekt ko'rinsa ehtiyotlik bilan oling, ko'rinmasa tekshirmang.",
                    "Ob'ekt chiqmasa 5 ta orqa urish va 5 ta ko'krak bosishini takrorlang.",
                    "103 ga qo'ng'iroq qiling yoki kimnidir yuborib yuboring.",
                ]
            },
            {
                'sarlavha': "Bolada kuyish",
                'tavsif': "Issiq suyuqlik, olov yoki elektr toki natijasida kuygan bolaga birinchi yordam. Tez va to'g'ri harakat qilish kuyishning og'irligini kamaytiradi.",
                'icon': '🔥',
                'tartib': 2,
                'tanlangan': False,
                'qadamlar': [
                    "Bolani issiqlik manbasidan darhol uzoqlashtiring.",
                    "Kuygan joyni 10-20 daqiqa oqar iliq suv ostida ushlab turing.",
                    "Muz, yog', tish pastasi yoki krem SURTMANG.",
                    "Kuygan joyni kiyim yoki taqinchoqlardan ehtiyotlik bilan tozalang.",
                    "Steril bint bilan yumshoq o'rang, lekin qattiq bog'lamang.",
                    "Katta kuyishlarda darhol 103 ga qo'ng'iroq qiling.",
                ]
            },
            {
                'sarlavha': "Bolada isitma",
                'tavsif': "Bolada harorat ko'tarilganda nima qilish kerak. Qachon uyda davolash mumkin va qachon shifokorga murojaat qilish zarur.",
                'icon': '🌡️',
                'tartib': 3,
                'tanlangan': False,
                'qadamlar': [
                    "Haroratni o'lchang. 38°C dan yuqori bo'lsa harakat boshlang.",
                    "Bolani yengil kiyintiring, yotqizing.",
                    "Ko'p suyuqlik bering: suv, sharbat, choy.",
                    "Yoshiga mos paracetamol yoki ibuprofen bering (dozani shifokordan so'rang).",
                    "Teri ustiga sovuq suv bilan arting (muz emas!).",
                    "39.5°C dan yuqori bo'lsa, 6 soatdan ortiq davom etsa shifokorga murojaat qiling.",
                ]
            },
            {
                'sarlavha': "Bolada qon ketish",
                'tavsif': "Bola jarohat olganda va qon ketayotganda birinchi yordam. Kichik va katta jarohatlar uchun turlicha yondashuv kerak.",
                'icon': '🩸',
                'tartib': 4,
                'tanlangan': False,
                'qadamlar': [
                    "Tinchlantirib, bolani xotirjam saqlang.",
                    "Toza mato yoki bint bilan jarohatni mahkam bosib turing.",
                    "Jarohat qo'l yoki oyoqda bo'lsa, yuqoriga ko'taring.",
                    "10-15 daqiqa davomida qo'yib yubormang.",
                    "Bint qonga to'lsa, ustiga yangi qavat qo'ying, ostini olmang.",
                    "Qon 15 daqiqadan keyin ham to'xtamasa shifokorga murojaat qiling.",
                ]
            },
            {
                'sarlavha': "Bolada zaharlanish",
                'tavsif': "Bola ishtaha ochuvchi dori, kimyoviy modda yoki zaharli o'simlik iste'mol qilgan bo'lsa nima qilish kerak.",
                'icon': '☠️',
                'tartib': 5,
                'tanlangan': False,
                'qadamlar': [
                    "Nima iste'mol qilinganini aniqlang. Idishni saqlang.",
                    "Darhol 103 ga qo'ng'iroq qiling.",
                    "Shifokor ruxsatisiz qustirmang!",
                    "Bola hushida bo'lsa oz-oz suv ichiring.",
                    "Nafas olishini va hushini kuzatib turing.",
                    "Hushidan ketsa yon holatga yotqizig.",
                ]
            },
            {
                'sarlavha': "Bolada suyak sinishi",
                'tavsif': "Bola yiqilib yoki zarba olganda suyak sinishi shubhasi bo'lsa nima qilish kerak. Noto'g'ri yordam ahvolni yomonlashtirishi mumkin.",
                'icon': '🦴',
                'tartib': 6,
                'tanlangan': False,
                'qadamlar': [
                    "Bolani qimirlatmang, tinch yotqizing.",
                    "Singan joyni tayoqcha yoki qattiq narsa bilan mahkamlang.",
                    "Singan suyakni o'zingiz o'rniga solishga urinmang.",
                    "Sovuq kompres qo'ying (muz to'g'ridan-to'g'ri teriga qo'ymang).",
                    "103 ga qo'ng'iroq qiling.",
                    "Bola yig'layotgan bo'lsa — bu yaxshi belgi, nafas olayapti.",
                ]
            },
            {
                'sarlavha': "Bolada tutqanoq",
                'tavsif': "Febrile (isitmalik) yoki epileptik tutqanoq paytida qanday harakat qilish kerak. Ko'p ota-onalar bu holatda noto'g'ri harakat qiladi.",
                'icon': '⚡',
                'tartib': 7,
                'tanlangan': False,
                'qadamlar': [
                    "Sakin bo'ling, vaqtni belgilang.",
                    "Bolani xavfsiz joyga yotqizing, boshini yon tomonga buring.",
                    "Atrofdan qattiq narsalarni olib qo'ying.",
                    "Bolani mahkam ushlamang, og'ziga narsa tiqmang.",
                    "Tutqanoq 5 daqiqadan uzun cho'zilsa 103 ga qo'ng'iroq qiling.",
                    "Tutqanoqdan keyin bolani kuzating, shifokorga ko'rsating.",
                ]
            },
            {
                'sarlavha': "Bolada hushdan ketish",
                'tavsif': "Bola to'satdan hushidan ketsa qanday harakat qilish kerak. Sababi turlicha bo'lishi mumkin — to'g'ri baholash muhim.",
                'icon': '😵',
                'tartib': 8,
                'tanlangan': False,
                'qadamlar': [
                    "Bolani xavfsiz joyga yotqizing.",
                    "Nafas olayotgan-olmayotganini tekshiring.",
                    "Nafas olayotgan bo'lsa yon holatga o'tkazing.",
                    "Darhol 103 ga qo'ng'iroq qiling.",
                    "Nafas olmayotgan bo'lsa YOR (yurak-o'pka resusitatsiyasi) boshlang.",
                    "Bola ongiga kelguncha kuzatib turing.",
                ]
            },
        ]

        for m in mavzular_data:
            mavzu, _ = BolalarMavzu.objects.get_or_create(
                sarlavha=m['sarlavha'],
                defaults={
                    'tavsif': m['tavsif'],
                    'icon': m['icon'],
                    'tartib': m['tartib'],
                    'tanlangan': m['tanlangan'],
                }
            )
            for i, matn in enumerate(m['qadamlar'], 1):
                BolalarQadam.objects.get_or_create(
                    mavzu=mavzu, tartib=i,
                    defaults={'matn': matn}
                )

        self.stdout.write(self.style.SUCCESS("Bolalar bo'limi ma'lumotlari yuklandi"))
        self.stdout.write(self.style.SUCCESS("Barcha ma'lumotlar muvaffaqiyatli yuklandi!"))
