# Generated by Django 5.2.12 on 2026-03-27 03:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FavquloddaRaqam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=200, verbose_name='Xizmat nomi')),
                ('raqam', models.CharField(max_length=20, verbose_name='Telefon raqami')),
                ('icon', models.CharField(default='📞', max_length=50, verbose_name='Icon')),
                ('tartib', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Favqulodda raqam',
                'verbose_name_plural': 'Favqulodda raqamlar',
                'ordering': ['tartib'],
            },
        ),
        migrations.CreateModel(
            name='Kategoriya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=200, verbose_name='Kategoriya nomi')),
                ('icon', models.CharField(default='🏥', max_length=50, verbose_name='Icon (emoji)')),
                ('rang', models.CharField(default='#e74c3c', max_length=7, verbose_name='Rang kodi')),
                ('tartib', models.PositiveIntegerField(default=0, verbose_name='Tartib raqami')),
                ('tavsif', models.TextField(blank=True, verbose_name='Qisqa tavsif')),
            ],
            options={
                'verbose_name': 'Kategoriya',
                'verbose_name_plural': 'Kategoriyalar',
                'ordering': ['tartib'],
            },
        ),
        migrations.CreateModel(
            name='TestSavol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('savol', models.TextField(verbose_name='Savol matni')),
                ('variant_a', models.CharField(max_length=300, verbose_name='A variant')),
                ('variant_b', models.CharField(max_length=300, verbose_name='B variant')),
                ('variant_c', models.CharField(max_length=300, verbose_name='C variant')),
                ('variant_d', models.CharField(max_length=300, verbose_name='D variant')),
                ('togri_javob', models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D')], max_length=1, verbose_name="To'g'ri javob")),
                ('izoh', models.TextField(blank=True, verbose_name='Javob izohi')),
                ('kategoriya', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='savollar', to='loyiha.kategoriya', verbose_name='Kategoriya')),
            ],
            options={
                'verbose_name': 'Test savol',
                'verbose_name_plural': 'Test savollari',
            },
        ),
        migrations.CreateModel(
            name='Qadam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tartib', models.PositiveIntegerField(verbose_name='Qadam raqami')),
                ('sarlavha', models.CharField(max_length=300, verbose_name='Qadam sarlavhasi')),
                ('tavsif', models.TextField(blank=True, verbose_name='Batafsil tushuntirish')),
                ('muhim', models.BooleanField(default=False, verbose_name='Muhim qadam (qizil)')),
                ('ovozli_matn', models.TextField(blank=True, help_text="Bo'sh qolsa sarlavha o'qiladi", verbose_name="Ovozli o'qish uchun matn")),
                ('kategoriya', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qadamlar', to='loyiha.kategoriya', verbose_name='Kategoriya')),
            ],
            options={
                'verbose_name': 'Qadam',
                'verbose_name_plural': 'Qadamlar',
                'ordering': ['kategoriya', 'tartib'],
                'unique_together': {('kategoriya', 'tartib')},
            },
        ),
    ]
