# Generated by Django 5.2.12 on 2026-03-28 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyiha', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=200, verbose_name='Dori nomi')),
                ('miqdor', models.CharField(blank=True, max_length=100, verbose_name='Miqdori (masalan: 500mg)')),
                ('tavsif', models.TextField(blank=True, verbose_name='Qisqa tavsif')),
                ('rasm', models.ImageField(blank=True, null=True, upload_to='dorilar/', verbose_name='Rasm')),
                ('muddati', models.DateField(blank=True, null=True, verbose_name='Yaroqlilik muddati')),
                ('eslatma_vaqti', models.TimeField(blank=True, null=True, verbose_name='Eslatma vaqti')),
                ('eslatma_tavsif', models.CharField(blank=True, max_length=300, verbose_name='Eslatma matni')),
                ('qoshilgan_sana', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Dori',
                'verbose_name_plural': 'Dorilar',
                'ordering': ['nomi'],
            },
        ),
    ]
