# Generated by Django 5.2.12 on 2026-03-28 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyiha', '0002_dori'),
    ]

    operations = [
        migrations.CreateModel(
            name='BolalarMavzu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sarlavha', models.CharField(max_length=300, verbose_name='Mavzu sarlavhasi')),
                ('tavsif', models.TextField(verbose_name='Tavsif')),
                ('rasm', models.ImageField(blank=True, null=True, upload_to='bolalar/', verbose_name='Rasm')),
                ('icon', models.CharField(default='🧒', max_length=50, verbose_name='Icon (emoji)')),
                ('tartib', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('tanlangan', models.BooleanField(default=False, verbose_name='Asosiy mavzu (featured)')),
            ],
            options={
                'verbose_name': 'Bolalar mavzusi',
                'verbose_name_plural': 'Bolalar mavzulari',
                'ordering': ['tartib'],
            },
        ),
        migrations.CreateModel(
            name='BolalarQadam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tartib', models.PositiveIntegerField(verbose_name='Qadam raqami')),
                ('matn', models.TextField(verbose_name='Qadam matni')),
                ('mavzu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qadamlar', to='loyiha.bolalarmavzu', verbose_name='Mavzu')),
            ],
            options={
                'verbose_name': 'Bolalar qadami',
                'verbose_name_plural': 'Bolalar qadamlari',
                'ordering': ['mavzu', 'tartib'],
            },
        ),
        migrations.CreateModel(
            name='VideoQollanma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sarlavha', models.CharField(max_length=300, verbose_name='Video sarlavhasi')),
                ('tavsif', models.TextField(blank=True, verbose_name='Qisqa tavsif')),
                ('youtube_url', models.URLField(verbose_name='YouTube havolasi')),
                ('tartib', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('qoshilgan_sana', models.DateTimeField(auto_now_add=True)),
                ('kategoriya', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='loyiha.kategoriya', verbose_name='Kategoriya')),
            ],
            options={
                'verbose_name': "Video qo'llanma",
                'verbose_name_plural': "Video qo'llanmalar",
                'ordering': ['tartib'],
            },
        ),
    ]
