# Generated by Django 5.2.12 on 2026-03-28 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyiha', '0003_bolalarmavzu_bolalarqadam_videoqollanma'),
    ]

    operations = [
        migrations.CreateModel(
            name='BolalarOgohlantirish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matn', models.CharField(max_length=300, verbose_name='Ogohlantirish matni')),
                ('tartib', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
            ],
            options={
                'verbose_name': 'Bolalar ogohlantirishи',
                'verbose_name_plural': 'Bolalar ogohlantirislari',
                'ordering': ['tartib'],
            },
        ),
        migrations.CreateModel(
            name='SaytSozlamalari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sayt_nomi', models.CharField(default='Vital Response', max_length=200, verbose_name='Sayt nomi')),
                ('logo_matn', models.CharField(default='+', max_length=50, verbose_name='Logo belgisi')),
                ('footer_matn', models.CharField(default='Vital Response First Aid Standards Care Authority in Emergencies', max_length=500, verbose_name='Footer matni')),
                ('hero_sarlavha', models.CharField(default='Hayotni saqlab qolishga tayyormisiz?', max_length=500, verbose_name='Hero sarlavha')),
                ('hero_tavsif', models.TextField(default="Vital Response — bu ekstremol vaziyatlarda professional birinchi yordam ko'rsatish bo'yicha siz bilishingiz kerak bo'lgan barchani o'rgatadigan platforma. Har bir soniya muhim.", verbose_name='Hero tavsif')),
                ('hero_rasm', models.ImageField(blank=True, null=True, upload_to='sayt/', verbose_name='Hero rasm')),
                ('hero_rasm_url', models.URLField(blank=True, default='https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?w=700&q=80', verbose_name='Hero rasm URL (agar rasm yuklanmasa)')),
                ('hero_tugma1_matn', models.CharField(default='Simulyatsiyani boshlash', max_length=100, verbose_name='Hero tugma 1 matni')),
                ('hero_tugma2_matn', models.CharField(default="Katalogga o'tish", max_length=100, verbose_name='Hero tugma 2 matni')),
                ('hero_stat_sarlavha', models.CharField(default='Haqiq pandemiya', max_length=200, verbose_name='Hero stat karta sarlavhasi')),
                ('hero_stat_tavsif', models.CharField(default='protokol tayyor', max_length=200, verbose_name='Hero stat karta tavsifi')),
                ('divider_1_raqam', models.CharField(default='01', max_length=10, verbose_name='Divider 1 raqam')),
                ('divider_1_matn', models.CharField(default='Tez yordam protokollari', max_length=200, verbose_name='Divider 1 matn')),
                ('divider_2_raqam', models.CharField(default='02', max_length=10, verbose_name='Divider 2 raqam')),
                ('divider_2_matn', models.CharField(default='Interaktiv testlar', max_length=200, verbose_name='Divider 2 matn')),
                ('divider_3_raqam', models.CharField(default='03', max_length=10, verbose_name='Divider 3 raqam')),
                ('divider_3_matn', models.CharField(default='Shoshilinch raqamlar', max_length=200, verbose_name='Divider 3 matn')),
                ('kategoriya_badge', models.CharField(default='Asosiy bilimlar', max_length=100, verbose_name='Kategoriya badge')),
                ('kategoriya_sarlavha', models.CharField(default='Favqulodda holatlar', max_length=200, verbose_name='Kategoriya sarlavha')),
                ('xarita_badge', models.CharField(default='Geolokatsiya', max_length=100, verbose_name='Xarita badge')),
                ('xarita_sarlavha', models.CharField(default='Yaqin atrafdagi shifoxonalar', max_length=200, verbose_name='Xarita sarlavha')),
                ('xarita_tavsif', models.TextField(default='Joylashuvingiz asosida eng yaqin tibbiy muassasalarni toping.', verbose_name='Xarita tavsif')),
                ('promo_badge', models.CharField(default='Bilim sinovi', max_length=100, verbose_name='Promo badge')),
                ('promo_sarlavha', models.CharField(default="Bilimingizni sinab ko'ring!", max_length=200, verbose_name='Promo sarlavha')),
                ('promo_tavsif', models.TextField(default="Birinchi yordam bo'yicha testni yechib, o'z bilimingizni baholang", verbose_name='Promo tavsif')),
                ('promo_tugma_matn', models.CharField(default='Testni boshlash', max_length=100, verbose_name='Promo tugma matni')),
                ('promo_stat1_raqam', models.CharField(default='10', max_length=20, verbose_name='Promo stat 1 raqam')),
                ('promo_stat1_label', models.CharField(default='Savollar', max_length=50, verbose_name='Promo stat 1 label')),
                ('promo_stat2_raqam', models.CharField(default='350', max_length=20, verbose_name='Promo stat 2 raqam')),
                ('promo_stat2_label', models.CharField(default='Max ball', max_length=50, verbose_name='Promo stat 2 label')),
                ('katalog_badge', models.CharField(default='Featured Guide', max_length=100, verbose_name='Katalog badge')),
                ('katalog_sarlavha', models.CharField(default="Birinchi tibbiy yordam bo'yicha bilimlar", max_length=300, verbose_name='Katalog sarlavha')),
                ('katalog_tavsif', models.TextField(default="Har bir soniya muhim! Favqulodda vaziyatlarda to'g'ri harakat qilishni o'rganing va yaqinlaringizni himoya qiling.", verbose_name='Katalog tavsif')),
                ('katalog_rasm', models.ImageField(blank=True, null=True, upload_to='sayt/', verbose_name='Katalog banner rasmi')),
                ('katalog_protokol_sarlavha', models.CharField(default='Urgent Medical Protocols', max_length=200, verbose_name="Protokol bo'lim sarlavhasi")),
                ('katalog_protokol_tavsif', models.CharField(default="Favqulodda tibbiy holatlar uchun bosqichma-bosqich ko'rsatmalar", max_length=300, verbose_name="Protokol bo'lim tavsifi")),
                ('shoshilinch_sarlavha', models.CharField(default='SHOSHILINCH YORDAM', max_length=200, verbose_name='Shoshilinch sarlavha')),
                ('shoshilinch_tavsif', models.CharField(default="Xotirjam bo'ling! Quyidagi qadamlarni bajaring:", max_length=300, verbose_name='Shoshilinch tavsif')),
                ('video_sarlavha', models.CharField(default="Video Qo'llanmalar", max_length=200, verbose_name='Video sahifa sarlavhasi')),
                ('video_tavsif', models.TextField(default="Vizual qo'llanmalar orqali birinchi yordam ko'rsatishni o'rganing. Professional shifokorlar tomonidan tayyorlangan video darsliklar.", verbose_name='Video sahifa tavsifi')),
                ('bolalar_sarlavha', models.CharField(default="Bolalar bo'limi", max_length=200, verbose_name='Bolalar sahifa sarlavhasi')),
                ('bolalar_tavsif', models.TextField(default="Bolalar uchun maxsus tayyorlangan birinchi yordam qo'llanmalari. Oddiy tilda, rasmlar bilan tushuntirilgan.", verbose_name='Bolalar sahifa tavsifi')),
                ('bolalar_maslahat', models.TextField(default="Bolaga birinchi yordam ko'rsatishda tinchlikni saqlang. Bolalar kattalar kayfiyatini sezadi - sizning xotirjamligingiz bolaga ham o'tadi.", verbose_name='Bolalar maslahat matni')),
                ('bolalar_cta_sarlavha', models.CharField(default="O'z qo'lingizda yengil tushuntiring!", max_length=200, verbose_name='Bolalar CTA sarlavha')),
                ('bolalar_cta_tavsif', models.TextField(default="Bolangizga birinchi yordam haqida o'yinlar va rasmlar orqali o'rgating. Bilim hayot saqlab qoladi.", verbose_name='Bolalar CTA tavsif')),
                ('dorilar_sarlavha', models.CharField(default='Mening Dorixonam', max_length=200, verbose_name='Dorilar sahifa sarlavhasi')),
                ('dorilar_tavsif', models.CharField(default='Sizning shaxsiy tibbiy inventaringiz va eslatmalaringiz.', max_length=300, verbose_name='Dorilar sahifa tavsifi')),
                ('dorilar_maslahat', models.TextField(default="Dorilarni quruq, salqin va quyosh nuri tushadigan joydan uzoqda saqlang. Bolalar va 5 yoshgacha bolalar qo'li yetmaydigan joylarda saqlang.", verbose_name='Dorilar maslahat matni')),
            ],
            options={
                'verbose_name': 'Sayt sozlamalari',
                'verbose_name_plural': 'Sayt sozlamalari',
            },
        ),
        migrations.CreateModel(
            name='ShoshilinchQadam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tartib', models.PositiveIntegerField(verbose_name='Qadam raqami')),
                ('sarlavha', models.CharField(max_length=300, verbose_name='Sarlavha')),
                ('tavsif', models.TextField(verbose_name='Tavsif')),
                ('muhim', models.BooleanField(default=False, verbose_name='Muhim qadam (highlighted)')),
                ('qongiroq_tugmasi', models.BooleanField(default=False, verbose_name="Qo'ng'iroq tugmasini ko'rsatish")),
            ],
            options={
                'verbose_name': 'Shoshilinch qadam',
                'verbose_name_plural': 'Shoshilinch qadamlar',
                'ordering': ['tartib'],
            },
        ),
        migrations.AddField(
            model_name='favquloddaraqam',
            name='asosiy',
            field=models.BooleanField(default=False, verbose_name='Asosiy raqam (tez yordam)'),
        ),
        migrations.AddField(
            model_name='qadam',
            name='rasm',
            field=models.ImageField(blank=True, null=True, upload_to='qadamlar/', verbose_name='Qadam rasmi'),
        ),
        migrations.AddField(
            model_name='testsavol',
            name='rasm',
            field=models.ImageField(blank=True, null=True, upload_to='test/', verbose_name='Savol rasmi'),
        ),
        migrations.AddField(
            model_name='videoqollanma',
            name='rasm',
            field=models.ImageField(blank=True, null=True, upload_to='videolar/', verbose_name='Custom thumbnail'),
        ),
    ]
