# Generated by Django 5.2.10 on 2026-03-29 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyiha', '0004_bolalarogohlantirish_saytsozlamalari_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saytsozlamalari',
            name='barcha_mavzular_matn',
            field=models.CharField(default='Barcha mavzular', max_length=100, verbose_name="'Barcha mavzular' matni"),
        ),
        migrations.AddField(
            model_name='saytsozlamalari',
            name='barchasi_filter',
            field=models.CharField(default='Barchasi', max_length=50, verbose_name='Video filter: Barchasi'),
        ),
        migrations.AddField(
            model_name='saytsozlamalari',
            name='barchasi_matn',
            field=models.CharField(default="Barchasini ko'rish", max_length=50, verbose_name="'Barchasini ko'rish' matni"),
        ),
        migrations.AddField(
            model_name='saytsozlamalari',
            name='batafsil_matn',
            field=models.CharField(default='Batafsil', max_length=50, verbose_name="'Batafsil' matni"),
        ),
        migrations.AddField(
            model_name='saytsozlamalari',
            name='batafsil_oqish_matn',
            field=models.CharField(default="Batafsil o'qish", max_length=100, verbose_name="'Batafsil o'qish' matni"),
        ),
        migrations.AddField(
            model_name='saytsozlamalari',
            name='bolalar_badge',
            field=models.CharField(default='Bolalar uchun', max_length=100, verbose_name='Bolalar badge matni'),
        ),
        migrations.AddField(
            model_name='saytsozlamalari',
            name='bolalar_maslahat_sarlavha',
            field=models.CharField(default='Foydali maslahatlar', max_length=100, verbose_name='Bolalar maslahat sarlavhasi'),
        ),
        migrations.AddField(
            model_name='saytsozlamalari',
            name='bolalar_ogohlantirish_sarlavha',
            field=models.CharField(default='Qizil belgili holatlarni bilasizmi?', max_length=200, verbose_name='Bolalar ogohlantirish sarlavhasi'),
        ),
        migrations.AddField(
            model_name='saytsozlamalari',
            name='boshqa_raqamlar_matn',
            field=models.CharField(default='Boshqa raqamlar', max_length=100, verbose_name="'Boshqa raqamlar' matni"),
        ),
        migrations.AddField(
            model_name='saytsozlamalari',
            name='dori_qoshish_matn',
            field=models.CharField(default="Yangi dori qo'shish", max_length=100, verbose_name="Dori qo'shish tugmasi"),
        ),
        migrations.AddField(
            model_name='saytsozlamalari',
            name='eslatmalar_matn',
            field=models.CharField(default='Eslatmalar', max_length=100, verbose_name="'Eslatmalar' sarlavhasi"),
        ),
        migrations.AddField(
            model_name='saytsozlamalari',
            name='favqulodda_raqamlar_matn',
            field=models.CharField(default='Favqulodda raqamlar', max_length=100, verbose_name="'Favqulodda raqamlar' sarlavhasi"),
        ),
        migrations.AddField(
            model_name='saytsozlamalari',
            name='footer_havola1',
            field=models.CharField(default='Maxfiylik siyosati', max_length=100, verbose_name='Footer havola 1'),
        ),
        migrations.AddField(
            model_name='saytsozlamalari',
            name='footer_havola2',
            field=models.CharField(default='Foydalanish shartlari', max_length=100, verbose_name='Footer havola 2'),
        ),
        migrations.AddField(
            model_name='saytsozlamalari',
            name='footer_havola3',
            field=models.CharField(default='Tibbiy ogohlantirish', max_length=100, verbose_name='Footer havola 3'),
        ),
        migrations.AddField(
            model_name='saytsozlamalari',
            name='footer_havola4',
            field=models.CharField(default='Sertifikatlangan yordam', max_length=100, verbose_name='Footer havola 4'),
        ),
        migrations.AddField(
            model_name='saytsozlamalari',
            name='foydali_maslahat_matn',
            field=models.CharField(default='Foydali maslahat', max_length=100, verbose_name="'Foydali maslahat' sarlavhasi"),
        ),
        migrations.AddField(
            model_name='saytsozlamalari',
            name='joylashuv_matn',
            field=models.CharField(default='Joylashuvni aniqlash', max_length=100, verbose_name='Joylashuv tugmasi matni'),
        ),
        migrations.AddField(
            model_name='saytsozlamalari',
            name='katalogga_matn',
            field=models.CharField(default="Katalogga o'tish", max_length=100, verbose_name="'Katalogga o'tish' tugmasi"),
        ),
        migrations.AddField(
            model_name='saytsozlamalari',
            name='mavjud_dorilar_matn',
            field=models.CharField(default='Mavjud dorilar', max_length=100, verbose_name="'Mavjud dorilar' sarlavhasi"),
        ),
        migrations.AddField(
            model_name='saytsozlamalari',
            name='muddati_xavf_matn',
            field=models.CharField(default='Muddati tugash xavfi', max_length=100, verbose_name='Muddati xavf sarlavhasi'),
        ),
        migrations.AddField(
            model_name='saytsozlamalari',
            name='muhim_badge',
            field=models.CharField(default='Muhim', max_length=50, verbose_name="'Muhim' badge matni"),
        ),
        migrations.AddField(
            model_name='saytsozlamalari',
            name='muhim_qadam_matn',
            field=models.CharField(default='Bu qadam juda muhim!', max_length=200, verbose_name='Muhim qadam ogohlantirish matni'),
        ),
        migrations.AddField(
            model_name='saytsozlamalari',
            name='nav_catalog',
            field=models.CharField(default='Katalog', max_length=50, verbose_name='Nav: Katalog'),
        ),
        migrations.AddField(
            model_name='saytsozlamalari',
            name='nav_emergency',
            field=models.CharField(default='SHOSHILINCH', max_length=50, verbose_name='Nav: Shoshilinch tugma'),
        ),
        migrations.AddField(
            model_name='saytsozlamalari',
            name='nav_home',
            field=models.CharField(default='Bosh sahifa', max_length=50, verbose_name='Nav: Bosh sahifa'),
        ),
        migrations.AddField(
            model_name='saytsozlamalari',
            name='nav_quiz',
            field=models.CharField(default='Test', max_length=50, verbose_name='Nav: Test'),
        ),
        migrations.AddField(
            model_name='saytsozlamalari',
            name='ovozli_yoriqnoma_matn',
            field=models.CharField(default="Ovozli yo'riqnoma", max_length=100, verbose_name="Ovozli yo'riqnoma tugmasi"),
        ),
        migrations.AddField(
            model_name='saytsozlamalari',
            name='qadam_matn',
            field=models.CharField(default='qadam', max_length=50, verbose_name="'qadam' so'zi"),
        ),
        migrations.AddField(
            model_name='saytsozlamalari',
            name='qidiruv_bosh_matn',
            field=models.CharField(default="bo'yicha natija topilmadi", max_length=200, verbose_name='Qidiruv: natija topilmadi'),
        ),
        migrations.AddField(
            model_name='saytsozlamalari',
            name='qidiruv_bosh_tavsif',
            field=models.CharField(default="Boshqa so'zlar bilan qidirib ko'ring", max_length=200, verbose_name="Qidiruv: boshqa so'zlar matni"),
        ),
        migrations.AddField(
            model_name='saytsozlamalari',
            name='qidiruv_btn',
            field=models.CharField(default='Qidirish', max_length=50, verbose_name='Qidiruv tugmasi matni'),
        ),
        migrations.AddField(
            model_name='saytsozlamalari',
            name='qidiruv_holatlar_matn',
            field=models.CharField(default='Holatlar', max_length=50, verbose_name='Qidiruv: Holatlar sarlavhasi'),
        ),
        migrations.AddField(
            model_name='saytsozlamalari',
            name='qidiruv_placeholder',
            field=models.CharField(default='Qidirish... (masalan: kuyish, qon ketish)', max_length=200, verbose_name='Qidiruv placeholder'),
        ),
        migrations.AddField(
            model_name='saytsozlamalari',
            name='qidiruv_qadamlar_matn',
            field=models.CharField(default='Qadamlar', max_length=50, verbose_name='Qidiruv: Qadamlar sarlavhasi'),
        ),
        migrations.AddField(
            model_name='saytsozlamalari',
            name='qidiruv_sarlavha',
            field=models.CharField(default='Qidiruv', max_length=100, verbose_name='Qidiruv sahifa sarlavhasi'),
        ),
        migrations.AddField(
            model_name='saytsozlamalari',
            name='qidiruv_tavsif',
            field=models.CharField(default="Nima bo'lganini yozing - biz yordam beramiz", max_length=200, verbose_name='Qidiruv sahifa tavsifi'),
        ),
        migrations.AddField(
            model_name='saytsozlamalari',
            name='qongiroq_matn',
            field=models.CharField(default="GA QO'NG'IROQ QILISH", max_length=100, verbose_name="Qo'ng'iroq tugmasi matni"),
        ),
        migrations.AddField(
            model_name='saytsozlamalari',
            name='shoshilinch_badge',
            field=models.CharField(default='SHOSHILINCH', max_length=50, verbose_name='Shoshilinch badge matni'),
        ),
        migrations.AddField(
            model_name='saytsozlamalari',
            name='test_ajoyib_matn',
            field=models.CharField(default='Ajoyib natija!', max_length=100, verbose_name='Test: Ajoyib natija matni'),
        ),
        migrations.AddField(
            model_name='saytsozlamalari',
            name='test_batafsil_matn',
            field=models.CharField(default='Batafsil natijalar', max_length=100, verbose_name='Test: Batafsil natijalar sarlavha'),
        ),
        migrations.AddField(
            model_name='saytsozlamalari',
            name='test_bosh_sahifa_matn',
            field=models.CharField(default='Bosh sahifaga', max_length=100, verbose_name='Test: Bosh sahifaga tugma'),
        ),
        migrations.AddField(
            model_name='saytsozlamalari',
            name='test_keyingi_matn',
            field=models.CharField(default='Keyingi', max_length=50, verbose_name='Test: Keyingi tugma'),
        ),
        migrations.AddField(
            model_name='saytsozlamalari',
            name='test_natija_btn',
            field=models.CharField(default="Natijani ko'rish", max_length=100, verbose_name="Test: Natijani ko'rish tugma"),
        ),
        migrations.AddField(
            model_name='saytsozlamalari',
            name='test_oldingi_matn',
            field=models.CharField(default='Oldingi', max_length=50, verbose_name='Test: Oldingi tugma'),
        ),
        migrations.AddField(
            model_name='saytsozlamalari',
            name='test_orqaning_matn',
            field=models.CharField(default="Ko'proq o'rganing!", max_length=100, verbose_name="Test: Ko'proq o'rganing matni"),
        ),
        migrations.AddField(
            model_name='saytsozlamalari',
            name='test_qayta_matn',
            field=models.CharField(default='Qayta topshirish', max_length=100, verbose_name='Test: Qayta topshirish tugma'),
        ),
        migrations.AddField(
            model_name='saytsozlamalari',
            name='test_tip_matn',
            field=models.CharField(default='Professional tip', max_length=100, verbose_name='Test: Tip sarlavhasi'),
        ),
        migrations.AddField(
            model_name='saytsozlamalari',
            name='test_yaxshi_matn',
            field=models.CharField(default='Yaxshi natija!', max_length=100, verbose_name='Test: Yaxshi natija matni'),
        ),
        migrations.AddField(
            model_name='saytsozlamalari',
            name='video_bosh_matn',
            field=models.CharField(default="Hozircha video qo'llanmalar qo'shilmagan.", max_length=200, verbose_name="Video bo'sh holat matni"),
        ),
        migrations.AddField(
            model_name='saytsozlamalari',
            name='xarita_placeholder',
            field=models.CharField(default="Xaritani ko'rish uchun joylashuvni aniqlang", max_length=200, verbose_name='Xarita placeholder matni'),
        ),
        migrations.AddField(
            model_name='saytsozlamalari',
            name='yaqin_dorixonalar_btn',
            field=models.CharField(default='Yaqin dorixonalar', max_length=100, verbose_name='Yaqin dorixonalar tugmasi'),
        ),
        migrations.AddField(
            model_name='saytsozlamalari',
            name='yaqin_kasalxona_matn',
            field=models.CharField(default='Eng yaqin kasalxonani topish', max_length=200, verbose_name='Yaqin kasalxona sarlavhasi'),
        ),
        migrations.AddField(
            model_name='saytsozlamalari',
            name='yaqin_kasalxonalar_btn',
            field=models.CharField(default='Yaqin kasalxonalar', max_length=100, verbose_name='Yaqin kasalxonalar tugmasi'),
        ),
    ]
