# Generated by Django 5.2.10 on 2026-04-19 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyiha', '0005_saytsozlamalari_barcha_mavzular_matn_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saytsozlamalari',
            name='footer_matn',
            field=models.CharField(default="Birinchi Tez Yordam — Favqulodda vaziyatlarda professional tibbiy yordam ko'rsatish platformasi", max_length=500, verbose_name='Footer matni'),
        ),
        migrations.AlterField(
            model_name='saytsozlamalari',
            name='hero_tavsif',
            field=models.TextField(default="Birinchi Tez Yordam — bu favqulodda vaziyatlarda professional birinchi yordam ko'rsatish bo'yicha siz bilishingiz kerak bo'lgan barchani o'rgatadigan platforma. Har bir soniya muhim.", verbose_name='Hero tavsif'),
        ),
        migrations.AlterField(
            model_name='saytsozlamalari',
            name='katalog_badge',
            field=models.CharField(default="Asosiy qo'llanma", max_length=100, verbose_name='Katalog badge'),
        ),
        migrations.AlterField(
            model_name='saytsozlamalari',
            name='katalog_protokol_sarlavha',
            field=models.CharField(default='Shoshilinch tibbiy protokollar', max_length=200, verbose_name="Protokol bo'lim sarlavhasi"),
        ),
        migrations.AlterField(
            model_name='saytsozlamalari',
            name='sayt_nomi',
            field=models.CharField(default='Birinchi Tez Yordam', max_length=200, verbose_name='Sayt nomi'),
        ),
    ]
