# Generated by Django 5.2.10 on 2026-04-19 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyiha', '0006_alter_saytsozlamalari_footer_matn_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramFoydalanuvchi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(unique=True, verbose_name='Telegram ID')),
                ('ism', models.CharField(blank=True, max_length=200, verbose_name='Ism')),
                ('username', models.CharField(blank=True, max_length=200, verbose_name='Username')),
                ('faol', models.BooleanField(default=True, verbose_name='Faol')),
                ('qoshilgan_sana', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Telegram foydalanuvchi',
                'verbose_name_plural': 'Telegram foydalanuvchilar',
            },
        ),
    ]
