# Generated by Django 5.2.10 on 2026-04-19 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyiha', '0007_telegramfoydalanuvchi'),
    ]

    operations = [
        migrations.AddField(
            model_name='dori',
            name='eslatma_kunlar',
            field=models.PositiveIntegerField(blank=True, help_text='Necha kun davomida eslatib tursin', null=True, verbose_name='Eslatma davomiyligi (kun)'),
        ),
    ]
