# Generated by Django 5.2.10 on 2026-04-20 02:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyiha', '0008_dori_eslatma_kunlar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dori',
            name='foydalanuvchi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dorilar', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi'),
        ),
        migrations.AddField(
            model_name='telegramfoydalanuvchi',
            name='foydalanuvchi',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='telegram', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi'),
        ),
        migrations.AlterField(
            model_name='saytsozlamalari',
            name='sayt_nomi',
            field=models.CharField(default='FirstAid.uz', max_length=200, verbose_name='Sayt nomi'),
        ),
        migrations.CreateModel(
            name='TelegramUlanishTokeni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=32, unique=True)),
                ('yaratilgan', models.DateTimeField(auto_now_add=True)),
                ('foydalanuvchi', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_token', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Telegram ulanish tokeni',
                'verbose_name_plural': 'Telegram ulanish tokenlari',
            },
        ),
    ]
