# Generated by Django 5.2.10 on 2026-05-12 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyiha', '0010_bolalarmalumot_videoqollanma_video_fayl_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saytsozlamalari',
            name='hero_tugma1_matn',
            field=models.CharField(default="Video qo'llanmalar", max_length=100, verbose_name='Hero tugma 1 matni'),
        ),
    ]
